// MAC -> property-graph (openCypher) projection of 'shop'. Generated by mac_to_graph.py — do not edit.
// 4 node labels, 2 relationship types. Concepts of class measure/enumeration are not nodes.

// --- node key constraints (runnable Cypher) ---
CREATE CONSTRAINT category_key IF NOT EXISTS FOR (n:Category) REQUIRE n.category_id IS UNIQUE;
CREATE CONSTRAINT product_key IF NOT EXISTS FOR (n:Product) REQUIRE n.sku IS UNIQUE;
CREATE CONSTRAINT customer_key IF NOT EXISTS FOR (n:Customer) REQUIRE n.customer_id IS UNIQUE;
CREATE CONSTRAINT order_key IF NOT EXISTS FOR (n:Order) REQUIRE n.order_id IS UNIQUE;

// --- node properties (schema; * = key) ---
//   (:Category {category_id*, name, parent_id})   <- categories
//   (:Product {sku*, name, category_id, list_price})   <- products
//   (:Customer {customer_id*, email, created_at})   <- customers
//   (:Order {order_id*, customer_id, status, placed_at, paid_at, shipped_at, delivered_at, gross_amount})   <- orders

// --- relationships (from MAC edges; FK columns become traversals) ---
//   (:Order)-[:PLACED_BY]->(:Customer)   on orders.customer_id = customers.customer_id
//   (:Product)-[:BELONGS_TO_CATEGORY]->(:Category)   on products.category_id = categories.category_id
