"""Freeze the interpreter's readings as a replayable plane, so a regression run needs no LLM.

WHY THIS EXISTS. Measured 2026-10-02: a full corpus run is 83 `claude -p` subprocesses and takes
**32.4 minutes**, of which the interpret step is essentially all of it -- the deterministic stages
(resolve -> plan -> execute -> grade) are milliseconds. So every regression of the PLANNER paid for
83 re-readings of questions whose readings had not changed, and the corpus is growing.

NOTHING HERE IS NEW MACHINERY. `mac_runtime.interpret.cached.CachedInterpreter` was built for
exactly this -- "replays RECORDED intents keyed by (normalized question, pack) ... Miss -> typed
error (never a silent guess). This is what makes the whole `ask` pipeline runnable with no
Bedrock" -- and `mac_console.ask_engine` already routes to it on `MAC_ASK_ENGINE=replay` +
`MAC_ASK_RECORDINGS=<dir>`, reading `<dir>/intents/*.yaml`. The only thing missing was a populated
plane. This writes it, from captures that already carry the Intent.

THE PLANE IS SEPARATE FROM `answers/`, AND THAT IS THE POINT. `answers/` is what a run produces and
it moves whenever anything moves; this is a REFERENCE INPUT that must not. Operator, 2026-10-02:
"this reference mockup shall be saved separately and not interfere with the one generated by
standard test run - which might also change from time to time." So:

  * `acceptance/intents/` is written ONLY by this module, invoked deliberately. No run writes it --
    `ask_engine`'s own `record` mode refuses to write inside a git work tree, which enforces the
    same separation from the other direction.
  * It is NOT in `bundleio._FINGERPRINT_TREES`. Those are the AUTHORED ORACLE -- what an answer is
    graded against -- and a frozen reading is an INPUT, not a judgement. Adding it would make every
    freeze mark every capture's evidence stale, which is the opposite of what staleness is for.
  * Provenance cannot ride inside a recording: `_RecordedIntentFile` is `extra="forbid"` over
    `{pack, question, as_of, intent}`. It goes in `MANIFEST.json` -- json, not yaml, because
    `load_recorded_intents` globs `*.yaml` and would try to parse a manifest as a recording.

WHAT IS FROZEN AND WHAT IS NOT. Only a question whose capture carries a usable Intent. A question
refused BY the interpreter (low confidence -> clarification) or failed IN it (a draft the grammar
rejects) has no reading to freeze, and inventing one would make the fast suite greener than the
real one. Those are reported, by id and reason, and the manifest records the count -- so the
replay suite can never silently cover less than it claims.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml
from pydantic import ValidationError

from mac_runtime.models import Intent

from sdk.acceptance.bundleio import atomic_write, check_qid

#: Where the frozen readings live, relative to the bundle. The `intents` leaf is not a choice:
#: `ask_engine.ReplayInterpreter` looks for `<MAC_ASK_RECORDINGS>/intents`, so pointing that env
#: var at `<bundle>/acceptance` finds this plane and `<bundle>/acceptance/interpret_errors`
#: beside it, with no new convention.
PLANE = "intents"
MANIFEST = "MANIFEST.json"


def pack_of(bundle: Path) -> str:
    """`<domain>/<dataset>`, the key `CachedInterpreter` filters on.

    Derived from the bundle path's last two segments because that is what
    `console_api._bundle_root(domain, dataset)` builds and what `ask_engine` passes as `pack`
    (`pack = f"{domain}/{dataset}"`). A recording whose pack does not match is silently skipped at
    load, so getting this wrong yields an empty cache rather than an error -- which is why it is
    derived from one place and asserted in the manifest.
    """
    bundle = Path(bundle).resolve()
    return f"{bundle.parent.name}/{bundle.name}"


def _questions(bundle: Path) -> dict[str, str]:
    """`id -> question text`, from the corpus. The captures do NOT carry the question text, and the
    cache keys on it, so the corpus is the only source."""
    path = bundle / "acceptance" / "questions.yaml"
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or []
    return {
        check_qid(q["id"], where="corpus question id"): str(q.get("question") or "")
        for q in raw
        if isinstance(q, dict) and q.get("id")
    }


def _readings(capture: dict[str, Any]) -> list[tuple[str | None, dict]]:
    """Every reading the interpreter produced for this question, as `(question_sent, intent)`.

    ONE RECORDING PER ATTEMPT, because the pipeline asks TWICE. When the evaluator judges the
    first answer SUSPECT it retries with a reviewer note appended to the question
    (`pipeline.question_with_suffixes`), and the cache keys on the question text -- so a plane
    holding only the bare question cache-MISSES on attempt 2. Measured 2026-10-02 on STORE-04
    ("When was the first store closed?"): attempt 1 `ok`, attempt 2 `error`, reported in the trace
    as `cache_miss ... [Reviewer note from attempt 1: ...]`. 7 of 83 captures retry.

    THE MISS WAS WORSE THAN A FALSE ERROR. The pipeline keeps attempt 1's answer when attempt 2
    fails, so the BOARD was unaffected and the gap hid -- while replay silently kept attempt 1's
    reading where the live run had taken attempt 2's. On STORE-04 attempt 2 had DROPPED the
    `closed` filter, so replay was accidentally the better of the two and faithful to neither.

    THE KEY IS `question_sent`, the exact text that attempt received, which every interpret stage
    records. The retry note is deterministic -- `evaluate.base.reviewer_hint` derives it from
    rule-based findings, not from a model -- so the suffixed key reproduces. Stripping the suffix
    instead was considered and rejected: it would make both attempts collide on one recording,
    which is the very conflation that hid this.

    TWO HOMES, AND THE TOP ONE IS CONDITIONAL. A capture writes `intent` at the top level only on
    a route that ANSWERED; on a refusal it is null even when the interpreter succeeded and the
    PLANNER refused (measured: MQ-03 and AGG-08 both reached `plan` with readings at 0.68 and
    0.95, both `intent: null` at the top). The stages carry it in every case.

    A LOW-CONFIDENCE READING IS KEPT, and that is not a loophole. The confidence gate is not part
    of the interpreter: `pipeline` calls `interpret_or_clarify(interpreter, ...)`, so the gate
    wraps whatever is returned and applies the same threshold. Replaying a declined reading
    re-derives the IDENTICAL clarification from the real gate. Filing these under
    `interpret_errors/` would have been a lie -- `InterpretErrorReason` has no low-confidence
    member, because a clarification is a legitimate outcome and not a failure.
    """
    out: list[tuple[str | None, dict]] = []
    for stage in capture.get("stages") or []:
        if stage.get("stage") != "interpret":
            continue
        det = stage.get("detail") or {}
        intent = det.get("intent")
        if isinstance(intent, dict) and intent.get("subject"):
            out.append((det.get("question_sent"), intent))
    if out:
        return out
    intent = capture.get("intent")
    return [(None, intent)] if isinstance(intent, dict) and intent.get("subject") else []


def freeze(bundle: Path, *, pack: str | None = None) -> dict[str, Any]:
    """Write `acceptance/intents/` from `acceptance/answers/`. Returns the manifest."""
    bundle = Path(bundle)
    acc = bundle / "acceptance"
    answers = acc / "answers"
    if not answers.is_dir():
        raise SystemExit(f"no captures to freeze: {answers} does not exist")
    pack = pack or pack_of(bundle)
    texts = _questions(bundle)

    out = acc / PLANE
    out.mkdir(parents=True, exist_ok=True)
    # EVERY STALE RECORDING GOES, and this is deliberate: a recording left behind for a question
    # the corpus no longer asks is a reading nothing can re-derive, and the cache would still
    # serve it. The plane is rewritten whole from the captures, never merged into.
    for old in out.glob("*.yaml"):
        old.unlink()

    frozen: dict[str, str] = {}
    skipped: dict[str, str] = {}
    errors: dict[str, str] = {}
    for path in sorted(answers.glob("*.yaml")):
        capture = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        qid = check_qid(capture.get("id") or path.stem, where="capture id")
        question = texts.get(qid)
        if not question:
            skipped[qid] = "no question text in the corpus"
            continue
        readings = _readings(capture)
        if not readings:
            # NO READING AT ALL -- the interpreter itself failed, so there is nothing to replay.
            # Recorded as the typed failure it was, under `interpret_errors/`, which
            # `ask_engine.ReplayInterpreter` reads beside `intents/` so a replay reaches this
            # outcome too rather than reporting a cache miss on a question that genuinely fails.
            errors[qid] = str(capture.get("error") or capture.get("route") or "no reading")
            continue
        for n, (sent, intent) in enumerate(readings, start=1):
            # VALIDATED HERE, NOT AT REPLAY. Parsed into the real `Intent` and dumped BY ALIAS, so
            # the plane holds the canonical shape whatever the capture happened to write. Measured
            # 2026-10-02: captures stored `compare.as_` (the python field name) which `CompareRef`
            # forbade on input, so a first cut of this plane could not be loaded at all -- the
            # replay died on AGG-08 instead of the freeze dying on it.
            try:
                canonical = Intent.model_validate(intent).model_dump(mode="json", by_alias=True)
            except ValidationError as exc:
                raise SystemExit(
                    f"{qid} attempt {n}: the captured reading is not a valid Intent, so it "
                    f"cannot be frozen.\n{exc}"
                ) from exc
            document = {
                "pack": pack,
                # WHAT THAT ATTEMPT WAS ASKED, suffix and all -- the cache's key.
                "question": sent or question,
                "as_of": str(capture.get("captured_at") or "")[:10] or None,
                "intent": canonical,
            }
            name = f"{qid}.yaml" if n == 1 else f"{qid}.attempt{n}.yaml"
            atomic_write(
                out / name,
                yaml.safe_dump(
                    {k: v for k, v in document.items() if v is not None}, sort_keys=False
                ),
            )
        frozen[qid] = f"{len(readings)} attempt(s), {capture.get('route') or ''}"

    # THE FAILURES, so a replay reaches every outcome the live run reaches.
    err_dir = acc / "interpret_errors"
    for old_err in err_dir.glob("*.yaml") if err_dir.is_dir() else ():
        old_err.unlink()
    if errors:
        err_dir.mkdir(parents=True, exist_ok=True)
        for qid, why in sorted(errors.items()):
            atomic_write(
                err_dir / f"{qid}.yaml",
                yaml.safe_dump(
                    {
                        "pack": pack,
                        "question": texts[qid],
                        # A DRAFT THE GRAMMAR REJECTS is a schema violation, which is what these
                        # are: `compare.against 'Q1 2023'` against an enum closed at `previous`.
                        "reason": "schema_violation",
                        "message": why,
                    },
                    sort_keys=False,
                ),
            )

    manifest = {
        "pack": pack,
        "frozen": len(frozen),
        "interpret_errors": len(errors),
        "skipped": len(skipped),
        "total_captures": len(frozen) + len(errors) + len(skipped),
        # THE PLANES THESE READINGS WERE TAKEN UNDER. A frozen reading is only as current as the
        # prompt and vocabulary that produced it: change those and the replay suite measures the
        # planner against yesterday's readings, which is legitimate and must be VISIBLE. These are
        # what makes that checkable without re-running the corpus.
        "ontology_fingerprint": _one(answers, "ontology_fingerprint"),
        "acceptance_fingerprint": _one(answers, "acceptance_fingerprint"),
        "captured_at": _one(answers, "captured_at"),
        "replay": {
            "MAC_ASK_ENGINE": "replay",
            "MAC_ASK_RECORDINGS": str((acc).resolve()),
        },
        "not_frozen": skipped,
        "recorded_as_failures": errors,
    }
    atomic_write(out / MANIFEST, json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return manifest


def _one(answers: Path, key: str) -> Any:
    """The value of `key` when every capture agrees, else the set of values.

    Honest rather than tidy: captures taken under two different ontologies are a real condition
    (a partial rerun), and collapsing that to the first value would hide it.
    """
    seen = set()
    for path in sorted(answers.glob("*.yaml")):
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if key in raw:
            seen.add(str(raw[key]))
    if not seen:
        return None
    return seen.pop() if len(seen) == 1 else sorted(seen)


def stale(bundle: Path) -> list[dict]:
    """Frozen readings whose KEY no longer matches the corpus question — newest defect first.

    A CACHE KEYED ON QUESTION TEXT GOES STALE SILENTLY THE MOMENT THE QUESTION IS RE-WORDED, and
    the replay reports that as a `cache_miss` against the QUESTION rather than against the plane.
    MEASURED 2026-10-02: the operator re-worded RC14 to pin an as_of
    ("...aged between 25 and 44 on 2022-12-10?"), the frozen plane still held a reading keyed on
    "How many customers are aged between 25 and 44?", and the next frozen run graded RC14 as
    `not evaluated: error`. The board lost a question and said nothing about why.

    SO STALENESS IS A REPORTED STATE, not an inference a reader has to make. A stale reading is not
    deleted here: deciding whether to re-run the question live is the operator's, and silently
    dropping a recording would make the fast suite quietly cover less than it claims.
    """
    texts = _questions(bundle)
    out: list[dict] = []
    plane = Path(bundle) / "acceptance" / PLANE
    if not plane.is_dir():
        return out
    for path in sorted(plane.glob("*.yaml")):
        qid, _, _ = path.stem.partition(".attempt")
        try:
            doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        except Exception:  # noqa: BLE001
            continue
        # attempt 2's key carries the reviewer note; compare only the question part
        key = str(doc.get("question") or "").split(" [Reviewer note", 1)[0]
        corpus = texts.get(qid)
        if not corpus:
            out.append({"question": qid, "why": "no such question in the corpus", "frozen": key})
            continue
        norm = lambda t: " ".join(str(t).split()).strip().casefold().rstrip("?!.")  # noqa: E731
        if norm(key) != norm(corpus):
            out.append(
                {"question": qid, "why": "the question was re-worded", "frozen": key, "corpus": corpus}
            )
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("bundle", help="path to the <domain>/<dataset> bundle dir")
    ap.add_argument("--pack", help="override the <domain>/<dataset> cache key")
    ap.add_argument(
        "--check",
        action="store_true",
        help="report frozen readings whose question was re-worded; exit 1 if any (writes nothing)",
    )
    a = ap.parse_args(argv)
    if a.check:
        rows = stale(Path(a.bundle))
        print(f"{len(rows)} stale frozen reading(s)")
        for r in rows:
            print(f"  {r['question']:12s} {r['why']}")
            print(f"  {'':12s} frozen: {str(r.get('frozen'))[:84]!r}")
            if r.get("corpus"):
                print(f"  {'':12s} corpus: {str(r['corpus'])[:84]!r}")
        if rows:
            print("\n  re-run those questions LIVE and re-freeze, or the fast suite grades them as errors")
        return 1 if rows else 0
    m = freeze(Path(a.bundle), pack=a.pack)
    print(f"pack {m['pack']}")
    print(f"frozen {m['frozen']} of {m['total_captures']} captures -> acceptance/{PLANE}/")
    if m["interpret_errors"]:
        print(f"recorded {m['interpret_errors']} interpret FAILURES -> acceptance/interpret_errors/")
        for qid, why in sorted(m["recorded_as_failures"].items()):
            print(f"  {qid:12s} {why[:90]}")
    if m["not_frozen"]:
        print(f"\nNOT frozen ({m['skipped']}) — no usable reading to replay:")
        for qid, why in sorted(m["not_frozen"].items()):
            print(f"  {qid:12s} {why[:90]}")
    print(f"\nreplay with:\n  MAC_ASK_ENGINE=replay MAC_ASK_RECORDINGS={m['replay']['MAC_ASK_RECORDINGS']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
