// MAC -> property-graph (openCypher) projection of 'tpch'. Generated by mac_to_graph.py — do not edit.
// 8 node labels, 8 relationship types. Concepts of class measure/enumeration are not nodes.

// --- node key constraints (runnable Cypher) ---
CREATE CONSTRAINT nation_key IF NOT EXISTS FOR (n:Nation) REQUIRE n.n_nationkey IS UNIQUE;
CREATE CONSTRAINT region_key IF NOT EXISTS FOR (n:Region) REQUIRE n.r_regionkey IS UNIQUE;
CREATE CONSTRAINT lineitem_key IF NOT EXISTS FOR (n:LineItem) REQUIRE n.l_orderkey IS UNIQUE;
CREATE CONSTRAINT orders_key IF NOT EXISTS FOR (n:Orders) REQUIRE n.o_orderkey IS UNIQUE;
CREATE CONSTRAINT part_key IF NOT EXISTS FOR (n:Part) REQUIRE n.p_partkey IS UNIQUE;
CREATE CONSTRAINT partsupp_key IF NOT EXISTS FOR (n:PartSupp) REQUIRE n.ps_partkey IS UNIQUE;
CREATE CONSTRAINT customer_key IF NOT EXISTS FOR (n:Customer) REQUIRE n.c_custkey IS UNIQUE;
CREATE CONSTRAINT supplier_key IF NOT EXISTS FOR (n:Supplier) REQUIRE n.s_suppkey IS UNIQUE;

// --- node properties (schema; * = key) ---
//   (:Nation {n_nationkey*, n_name, n_regionkey, n_comment})   <- nation
//   (:Region {r_regionkey*, r_name, r_comment})   <- region
//   (:LineItem {l_orderkey*, l_linenumber, l_partkey, l_suppkey, l_quantity, l_extendedprice, l_discount, l_tax, l_returnflag, l_linestatus, l_shipdate, l_commitdate, l_receiptdate, l_shipmode, l_comment})   <- lineitem
//   (:Orders {o_orderkey*, o_custkey, o_orderstatus, o_totalprice, o_orderdate, o_orderpriority, o_comment})   <- orders
//   (:Part {p_partkey*, p_name, p_mfgr, p_brand, p_type, p_size, p_retailprice, p_comment})   <- part
//   (:PartSupp {ps_partkey*, ps_suppkey, ps_availqty, ps_supplycost, ps_comment})   <- partsupp
//   (:Customer {c_custkey*, c_name, c_nationkey, c_phone, c_acctbal, c_mktsegment, c_comment})   <- customer
//   (:Supplier {s_suppkey*, s_name, s_nationkey, s_phone, s_acctbal, s_comment})   <- supplier

// --- relationships (from MAC edges; FK columns become traversals) ---
//   (:Nation)-[:IN_REGION]->(:Region)   on nation.n_regionkey = region.r_regionkey
//   (:Customer)-[:FROM_NATION]->(:Nation)   on customer.c_nationkey = nation.n_nationkey
//   (:Supplier)-[:FROM_NATION]->(:Nation)   on supplier.s_nationkey = nation.n_nationkey
//   (:PartSupp)-[:OF_PART]->(:Part)   on partsupp.ps_partkey = part.p_partkey
//   (:PartSupp)-[:FROM_SUPPLIER]->(:Supplier)   on partsupp.ps_suppkey = supplier.s_suppkey
//   (:Orders)-[:PLACED_BY]->(:Customer)   on orders.o_custkey = customer.c_custkey
//   (:LineItem)-[:PART_OF_ORDER]->(:Orders)   on lineitem.l_orderkey = orders.o_orderkey
//   (:LineItem)-[:SUPPLIED_VIA]->(:PartSupp)   on lineitem.l_partkey = partsupp.ps_partkey AND lineitem.l_suppkey = partsupp.ps_suppkey
