#!/usr/bin/env python3
"""ingest_signals — project OPEN/REOPENED plane-3 annotations into VSC work-items.

Reads the `annotations/` tree by an EXPLICITLY-PASSED path (it never imports or globs the
wiki tree — the sdk<->annotations edge is a declared, path-scoped read), and writes
`worklog/<domain>/<dataset>/OPEN.md` — the developer backlog, sorted by type-weight
(ruling > concern > question > comment). Deterministic: same annotations -> same work-items.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

_WEIGHT = {"ruling": 0, "concern": 1, "question": 2, "comment": 3}


def ingest(ann_root: Path, worklog_root: Path) -> int:
    ann_root, worklog_root = Path(ann_root), Path(worklog_root)
    total = 0
    domains = sorted(p for p in ann_root.iterdir() if p.is_dir()) if ann_root.exists() else []
    for dd in domains:
        for ds in sorted(p for p in dd.iterdir() if p.is_dir()):
            items = [
                a
                for f in sorted(ds.glob("*.yaml"))
                if (a := yaml.safe_load(f.read_text()) or {}).get("status") in ("open", "reopened")
            ]
            if not items:
                continue
            items.sort(key=lambda a: (_WEIGHT.get(a.get("type"), 9), a.get("created_at", "")))
            lines = [
                f"# Work-items — {dd.name}/{ds.name}",
                "",
                f"Projected from {len(items)} open/reopened annotation(s). "
                "Generated by ingest_signals — do not edit.",
                "",
            ]
            for a in items:
                anchor = (a.get("anchor") or {}).get("concept_id") or "(page-level)"
                lines.append(
                    f"- **[{a.get('type', '?').upper()}]** `{a['id']}` on `{anchor}` — "
                    f"{(a.get('body') or '').strip()[:200]}"
                )
                if a.get("type") == "ruling" and a.get("ruling"):
                    r = a["ruling"]
                    lines.append(
                        f"    - RULING: outcome={r.get('expected_outcome')} "
                        f"value={r.get('expected_value')} — RE-DERIVE by executing "
                        "`sql_contains` under the gate; do NOT copy the scalar."
                    )
            out = worklog_root / dd.name / ds.name
            out.mkdir(parents=True, exist_ok=True)
            (out / "OPEN.md").write_text("\n".join(lines) + "\n")
            total += len(items)
    print(f"ingest_signals: {total} open work-item(s) -> {worklog_root}")
    return total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--annotations", required=True, help="the annotations/ tree")
    ap.add_argument("--worklog", required=True, help="the worklog/ output tree")
    a = ap.parse_args()
    ingest(a.annotations, a.worklog)
    return 0


if __name__ == "__main__":
    sys.exit(main())
