#!/usr/bin/env python3
"""gen_decisions_index.py — the decision record index, READ off the records and off git history.

WHAT WAS WRONG WITH THE HAND-WRITTEN ONE. `decisions/README.md` was 25 lines carrying nine facts
restated from files that already hold them: a six-row "retired records" table, and three prose
overrides naming which records are superseded, which are designed-but-not-enforced, and which use
bundle-relative paths. Measured 2026-10-04, every one of the three was incomplete:

  * the retired table listed SIX removals. `git log --diff-filter=D -- decisions/` names SEVEN —
    `decisions/PLAN.yaml` was retired 2026-09-16 and no longer exists, and was never listed, so a
    pointer that still named it had nowhere to land — which is the one job the table had.
  * "Paths inside `DELIVERABLES-*`, `DNA-*` and `PROTOCOL-2026-09-29_guardrails.md` are
    bundle-relative" named THREE records. Five carry that declaration in their own text.
  * "Retained but marked designed, not enforced … (cited as `RECORD:` by `sdk/connector/` and two
    `sdk/gate/*_floor.txt` baselines, so it cannot go)" is a citation count typed by hand. It is
    countable: `git ls-files` plus a substring search answers it for every record at once.

NOTHING HERE IS GUESSED, AND WHAT IS MISSING IS ON THE PAGE. A record's KIND comes from its filename
prefix. Its STATE comes from frontmatter if a record carries any, else from a `Status:` line in the
head of its body. Measured on this tree, no record carries frontmatter at all and seven carry no
status line either — so seven records' state is UNKNOWN, and the page says UNKNOWN for them rather
than reading `PROPOSED-` in a filename as a ratification. The filename prefix is a separate column
precisely so the two are never conflated.

WHY GIT IS A SOURCE. A removed record is not on disk; that is the point of removing it. The only
place it still exists is history, so the retired list is derived from `git log --diff-filter=D`
rather than retyped. A tree where git cannot answer gets exit 2 (could not run), never a page with a
silently empty retired section.

THE CHECK DOES NOT ONLY RE-RENDER. Byte-comparing the page against a fresh render catches a page
someone edited and CANNOT catch this renderer dropping a row — the measured defect in
`gen_schema_shapes.py --check`, where the comparator and the renderer are the same code and agree by
construction. So `--check` also asserts, from two sources neither of which is the renderer, that
every record ON DISK is linked from the page, and every record GIT RECORDS AS DELETED is named on
it. Three questions, three kinds of evidence.

    python3 tools/gen_decisions_index.py              # write decisions/README.md
    python3 tools/gen_decisions_index.py --check      # exit 1 if stale or incomplete
    python3 tools/gen_decisions_index.py --self-test  # one mutant per reject class + a clean fixture
"""
from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys
import tempfile

try:
    import yaml
except ImportError:                                           # pragma: no cover
    print("COULD NOT RUN: pyyaml is not installed", file=sys.stderr)
    raise SystemExit(2)

SELF = pathlib.Path(__file__).resolve()
TOOLS = SELF.parent
ROOT = TOOLS.parent

BANNER = "<!-- GENERATED by tools/gen_decisions_index.py — do not edit; regenerate. -->"
LINK_RE = re.compile(r"\]\(([^)\s]+)\)")
H1_RE = re.compile(r"^#\s+(.*)$", re.M)
#: `PROPOSED-2026-09-29_guardrails.md`, `2026-09-10_packaging-and-release-surface.md` — a kind prefix
#: is OPTIONAL and its absence is reported, not filled in.
NAME_RE = re.compile(r"^(?:(?P<kind>[A-Z][A-Z-]*)-)?(?P<date>\d{4}-\d{2}-\d{2})_(?P<slug>.+)$")
#: Every spelling of a status line these records actually use: `STATUS: X`, `**Status:** X`,
#: `**Status: X**`. Nothing is inferred when none matches.
STATE_RE = re.compile(r"^\s*\*{0,2}\s*status\s*:\s*\*{0,2}\s*(?P<state>.+?)\s*$", re.I | re.M)
SUPERSEDE_RE = re.compile(
    r"supersede[sd]?(?:\s+(?:in|on)?\s*\d{4}-\d{2}-\d{2})?\s+by\s+`?(?P<name>[\w.\-]+\.(?:md|yaml))`?",
    re.I)
#: How far into a record's body a state declaration is looked for. Every record that declares one
#: today declares it in its first few lines; a window is stated rather than silently unbounded, so a
#: stray "status:" 400 lines down cannot be read as the record's own verdict.
HEAD_LINES = 30
CELL_WIDTH = 150


class CouldNotRun(Exception):
    """A source this index is DERIVED FROM is unreadable. Exit 2 — never a verdict."""


def _gate():
    """`check_dangling_references` itself, so "declares bundle-relative paths" and "declares designed,
    not enforced" mean here EXACTLY what they mean to the gate that acts on them — its regexes and its
    head window, imported rather than restated. None when it cannot be imported, and the page then
    omits those sections instead of asserting something it did not read."""
    sys.path.insert(0, str(TOOLS))
    try:
        import check_dangling_references as cdr
        return cdr
    except Exception:                                          # pragma: no cover
        return None


GATE = _gate()


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# where things are
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def decisions_dir(root: pathlib.Path) -> pathlib.Path:
    return root / "decisions"


def index_path(root: pathlib.Path) -> pathlib.Path:
    return decisions_dir(root) / "README.md"


def record_files(root: pathlib.Path) -> list[pathlib.Path]:
    d = decisions_dir(root)
    if not d.is_dir():
        raise CouldNotRun(f"{d} is not a directory")
    return sorted(p for p in d.glob("*.md") if p.name != "README.md")


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# git — the only home of a record that has been removed
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def git(root: pathlib.Path, *args: str) -> str:
    try:
        out = subprocess.run(["git", "-C", str(root), *args],
                             capture_output=True, text=True, timeout=120)
    except (OSError, subprocess.SubprocessError) as exc:
        raise CouldNotRun(f"git is not runnable here ({exc}); the retired-record list is derived "
                          f"from history and cannot be guessed")
    if out.returncode != 0:
        raise CouldNotRun(f"`git {' '.join(args)}` failed in {root}: "
                          f"{(out.stderr or out.stdout).strip().splitlines()[:1]}")
    return out.stdout


def removed_records(root: pathlib.Path) -> list[dict]:
    """Every file git records as DELETED from decisions/ and absent from disk now, newest first."""
    raw = git(root, "log", "--diff-filter=D", "--no-renames", "--date=short",
              "--format=%x01%h%x09%ad%x09%s", "--name-only", "--", "decisions/")
    out: dict[str, dict] = {}
    commit: dict | None = None
    for line in raw.splitlines():
        if line.startswith("\x01"):
            h, date, subject = line[1:].split("\t", 2)
            commit = {"commit": h, "date": date, "subject": subject}
            continue
        path = line.strip()
        if not path or commit is None or not path.startswith("decisions/"):
            continue
        if (root / path).exists():
            continue                       # deleted once and put back; it is a live record, not gone
        out.setdefault(path, dict(commit, path=path, name=path.split("/", 1)[1]))
    return sorted(out.values(), key=lambda r: (r["date"], r["name"]), reverse=True)


def counting_itself(root: pathlib.Path) -> set[str]:
    """This generator and whatever gate delegates to it — derived, not listed.

    A citation here means a POINTER THAT WOULD DANGLE if the record were removed. This file names
    records in its own documentation as the evidence for why it exists, and counting those made the
    index's own counts move whenever its docstring did. The counter does not count itself.
    """
    out = {f"tools/{SELF.name}"}
    for p in sorted((root / "tools").glob("check_*.py")):
        if re.search(rf"\bimport\s+{re.escape(SELF.stem)}\b",
                     p.read_text(encoding="utf-8", errors="replace")):
            out.add(f"tools/{p.name}")
    return out


def citations(root: pathlib.Path, names: list[str]) -> dict[str, list[str]]:
    """For each record, the TRACKED files outside decisions/ that name it. One pass, not N."""
    skip = counting_itself(root)
    tracked = [f for f in git(root, "ls-files").split("\n")
               if f and not f.startswith("decisions/") and f not in skip]
    hits: dict[str, list[str]] = {n: [] for n in names}
    for rel in tracked:
        p = root / rel
        if not p.is_file():
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for n in names:
            if n in text:
                hits[n].append(rel)
    return hits


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# reading one record
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def front_matter(text: str) -> dict | None:
    """Frontmatter if the record carries any. Today none does; another branch may add `state:`."""
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end < 0:
        return None
    try:
        parsed = yaml.safe_load(text[text.index("\n") + 1:end])
    except yaml.YAMLError:
        return None
    return parsed if isinstance(parsed, dict) else None


def trim_state(raw: str) -> str:
    """The DECLARATION, not the paragraph it opens. A stated rule, applied the same way every time.

    These records write their state three ways — `STATUS: ACCEPTED (option C) · DATE: …`,
    `**Status: PROPOSED.** <prose>`, `**Status:** PROPOSED. <prose>` — so the state ends at whichever
    comes first: the close of the bold run it was written in, a ` · ` separator, or the end of its
    first sentence. Taking the whole line instead put four records' opening prose in the table and
    left stray `**` in it.
    """
    s = raw.strip()
    for stop in ("**", " · "):
        i = s.find(stop)
        if i > 0:
            s = s[:i]
    s = s.strip()
    m = re.match(r"^(.*?[.!])(?:\s|$)", s)
    if m:
        s = m.group(1)
    return s.strip().strip("*").strip().rstrip(".").strip()


def describe(path: pathlib.Path, root: pathlib.Path) -> dict:
    """One record. `state_from` names the EVIDENCE, so a reader can tell a declaration from a gap."""
    text = path.read_text(encoding="utf-8", errors="replace")
    m = NAME_RE.match(path.stem)
    kind = (m.group("kind") if m and m.group("kind") else None)
    date = m.group("date") if m else None

    state = None
    state_from = "UNKNOWN — no frontmatter and no Status: line in its first %d lines" % HEAD_LINES

    fm = front_matter(text)
    if fm:
        # `state:` is the key another branch is adding; `status:` is how the rest of this repository
        # spells it. Either is a declaration and is read as one; neither is required to exist.
        for key in ("state", "status"):
            if fm.get(key) is not None:
                state, state_from = trim_state(str(fm[key])), f"frontmatter `{key}:`"
                break

    head = "\n".join(text.splitlines()[:HEAD_LINES])
    if state is None:
        sm = STATE_RE.search(head)
        if sm:
            state = trim_state(sm.group("state"))
            state_from = "a `Status:` line in the body"

    smm = SUPERSEDE_RE.search(head)
    h1 = H1_RE.search(text)
    return {"name": path.name, "kind": kind, "date": date, "state": state, "state_from": state_from,
            "superseded_by": smm.group("name") if smm else None,
            "title": h1.group(1).strip() if h1 else None,
            "lines": len(text.splitlines()),
            # TWO WINDOWS, ON PURPOSE. The first is what `check_dangling_references` reads and acts
            # on; the second is anywhere in the record's head. A record that declares bundle-relative
            # paths outside the gate's window has made a declaration nothing reads, and the gap
            # between the two columns is the finding.
            "designed": None if GATE is None else bool(GATE._declares_design(path)),
            "bundle_relative": None if GATE is None else bool(GATE._declares_bundle_relative(path)),
            "bundle_relative_head": (None if GATE is None
                                     else bool(GATE.BUNDLE_DECL_RE.search(head)))}


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# rendering
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def cell(text, width: int = CELL_WIDTH) -> str:
    if text is None:
        return "—"
    s = re.sub(r"\s+", " ", str(text)).strip()
    if len(s) > width:
        s = s[:width - 1].rstrip() + "…"
    return s.replace("|", "\\|") or "—"


def render(root: pathlib.Path) -> str:
    records = [describe(p, root) for p in record_files(root)]
    if not records:
        raise CouldNotRun(f"{decisions_dir(root)} holds no record to index")
    removed = removed_records(root)
    cited = citations(root, [r["name"] for r in records])

    unknown = [r for r in records if r["state"] is None]
    bundle_rel = [r for r in records if r["bundle_relative"]]
    bundle_head = [r for r in records if r["bundle_relative_head"]]
    unseen_decl = [r for r in bundle_head if not r["bundle_relative"]]
    designed = [r for r in records if r["designed"]]
    superseded = [r for r in records if r["superseded_by"]]
    kinds: dict[str, int] = {}
    for r in records:
        k = r["kind"] or "— (no kind prefix)"
        kinds[k] = kinds.get(k, 0) + 1

    L: list[str] = []
    A = L.append

    A("---")
    A("title: decisions/ — the record, indexed")
    A(f"status: GENERATED by tools/gen_decisions_index.py from the records themselves and from git "
      f"history — {len(records)} record(s) on disk, {len(removed)} removed. Every name, state and "
      f"count below is read; none is typed. Held by tools/check_decisions_index.py.")
    A("scope: META — this index names this repository's own decision records. No business domain, "
      "warehouse or vendor appears here.")
    A("---")
    A("")
    A(BANNER)
    A("")
    A("# decisions/ — the record")
    A("")
    A("Records here are written by agents as `PROPOSED` and ratified by the operator as `RULED`")
    A("(CORE §3). A record stays until it is superseded or describes only retired shapes; then it is")
    A("removed with `git rm` so history keeps it, and the removal is listed below so a pointer that")
    A("still names it has somewhere to land.")
    A("")
    A("**This index is generated, and it distinguishes what a record DECLARES from what its filename")
    A("merely suggests.** The `kind` column is the filename prefix. The `state` column is a")
    A("declaration — frontmatter if a record carries any, else a `Status:` line in the head of its")
    A(f"body — and where there is neither it says **UNKNOWN**, because reading `PROPOSED-` in a")
    A("filename as a ratification is the guess this page refuses to make. The retired list is derived")
    A("from `git log --diff-filter=D`, which is the only place a removed record still exists.")
    A("")

    A("## What is here")
    A("")
    A("| | count |")
    A("|---|---|")
    A(f"| records on disk | {len(records)} |")
    A(f"| …whose state is DECLARED | {len(records) - len(unknown)} |")
    A(f"| …whose state is **UNKNOWN** | {len(unknown)} |")
    A(f"| records git records as removed | {len(removed)} |")
    A(f"| records naming what supersedes them | {len(superseded)} |")
    if GATE is not None:
        A(f"| records declaring *designed, not enforced* | {len(designed)} |")
        A(f"| records declaring bundle-relative paths, where the gate reads | {len(bundle_rel)} |")
        A(f"| …and anywhere in their first {HEAD_LINES} lines | {len(bundle_head)} |")
    A("")
    A("By filename prefix: " + ", ".join(f"**{n}** × `{k}`" for k, n in
                                         sorted(kinds.items(), key=lambda kv: (-kv[1], kv[0]))) + ".")
    A("")

    A("## The records")
    A("")
    A("`cited by` counts TRACKED files outside `decisions/` that name the record — the test of whether")
    A("removing it would leave a pointer with nowhere to land.")
    A("")
    A("| record | kind (filename) | state (declared) | where the state was read | cited by |")
    A("|---|---|---|---|---|")
    for r in records:
        hits = cited.get(r["name"], [])
        where = ", ".join(f"`{h}`" for h in hits[:3]) + (f" +{len(hits) - 3} more" if len(hits) > 3 else "")
        A(f"| [`{r['name']}`]({r['name']}) | {r['kind'] or '**— none**'} "
          f"| {cell(r['state']) if r['state'] else '**UNKNOWN**'} | {cell(r['state_from'], 70)} "
          f"| {len(hits)}{(' — ' + where) if hits else ''} |")
    A("")

    if unknown:
        A("### State UNKNOWN — a declared gap, not a guess")
        A("")
        A(f"**{len(unknown)} of {len(records)}** record(s) declare no state this index can read. A")
        A("filename prefix is not a state: an agent may only write `PROPOSED`, so the prefix says who")
        A("wrote it, not whether anyone ruled on it. Each of these needs a `Status:` line or")
        A("frontmatter in the record itself; until then the honest value is UNKNOWN.")
        A("")
        for r in unknown:
            A(f"* [`{r['name']}`]({r['name']}) — filename prefix `{r['kind'] or 'none'}`, "
              f"{r['lines']} lines, titled \"{cell(r['title'], 90)}\"")
        A("")

    A("## Removed records — where a pointer that still names one should land")
    A("")
    if removed:
        A(f"**{len(removed)}** file(s), read from `git log --diff-filter=D -- decisions/`. The reason is")
        A("the commit that removed it, quoted; the content is in history at that commit.")
        A("")
        A("| removed | file | removed by (commit · subject) |")
        A("|---|---|---|")
        for r in removed:
            A(f"| {r['date']} | `{r['name']}` (retired) | `{r['commit']}` · {cell(r['subject'], 110)} |")
    else:
        A("None: git records no deletion under `decisions/` in the history this checkout carries.")
    A("")

    if superseded:
        A("## Superseded, by the record's own words")
        A("")
        A("| record | names as its successor | successor is on disk |")
        A("|---|---|---|")
        for r in superseded:
            here = (decisions_dir(root) / r["superseded_by"]).is_file()
            A(f"| [`{r['name']}`]({r['name']}) | `{r['superseded_by']}` (supersedes) "
              f"| {'yes' if here else '**no — removed or elsewhere**'} |")
        A("")

    if GATE is not None and designed:
        A("## Declared *designed, not enforced*")
        A("")
        A("Read with `check_dangling_references`'s own reader, so this says what that gate sees: a")
        A("record carrying the phrase in its head has its unbuilt paths treated as unlocated rather")
        A("than dangling.")
        A("")
        for r in designed:
            n = len(cited.get(r["name"], []))
            A(f"* [`{r['name']}`]({r['name']}) — cited by {n} tracked file(s) outside `decisions/`"
              + (", so removing it would orphan those pointers" if n else ""))
        A("")

    if GATE is not None and bundle_head:
        A("## Declared bundle-relative paths")
        A("")
        A("`data/…`, `ontology/…`, `acceptance/…` and the like in these records name files of an")
        A("APPLIED ontology, not paths in this repository. **Read** means read by")
        A("`check_dangling_references`, whose own reader looks only at a record's opening lines; the")
        A("second column is the same declaration found anywhere in the record's head, so a declaration")
        A("the gate cannot see shows up as a gap between the two rather than as nothing.")
        A("")
        A("| record | the gate reads it | declared in its head |")
        A("|---|---|---|")
        for r in bundle_head:
            A(f"| [`{r['name']}`]({r['name']}) | {'yes' if r['bundle_relative'] else '**no**'} | yes |")
        A("")
        if unseen_decl:
            A(f"**{len(unseen_decl)} record(s) declare bundle-relative paths where the gate does not "
              f"look**, so their bundle paths are judged as this repository's: "
              + ", ".join(f"[`{r['name']}`]({r['name']})" for r in unseen_decl) +
              ". Moving the declaration into the opening lines is the fix; this index only reports it.")
            A("")

    A("## What holds this index")
    A("")
    A("`python3 tools/gen_decisions_index.py` writes this page. `python3")
    A("tools/check_decisions_index.py` — which `tools/run_framework_gates.sh` runs, because the suite")
    A("globs `check_*.py` — rejects it on four separate grounds: the index is **missing**; the index is")
    A("**stale** against a fresh render; a record **exists on disk and this index does not link it**;")
    A("a record **git records as removed is not named on it**. The last two are asserted from the")
    A("filesystem and from git history against the text of this page as written, not from the")
    A("renderer's own model — so a renderer that silently drops a row is caught by evidence that")
    A("cannot agree with it.")
    A("")
    return "\n".join(L) + "\n"


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# the check — three kinds of question, four rejects
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def link_targets(text: str) -> set[str]:
    out = set()
    for raw in LINK_RE.findall(text):
        if "://" in raw or raw.startswith(("#", "mailto:")):
            continue
        out.add(raw.split("#", 1)[0].strip("`"))
    return out


def check(root: pathlib.Path) -> tuple[list[str], dict]:
    index = index_path(root)
    records = record_files(root)
    removed = removed_records(root)
    counts = {"records": len(records), "removed": len(removed)}
    rejects: list[str] = []

    if not index.is_file():
        rejects.append(f"[missing-index] decisions/README.md — the record has no index; run "
                       f"`python3 tools/gen_decisions_index.py`")
        return rejects, counts

    on_disk = index.read_text(encoding="utf-8")
    if on_disk != render(root):
        rejects.append("[stale-index] decisions/README.md — the records moved and the index did not; "
                       "run `python3 tools/gen_decisions_index.py`")

    #: INDEPENDENT ASSERTION 1 — the filesystem. Re-rendering and byte-comparing cannot catch THIS
    #: renderer dropping a row, because the comparator and the renderer are the same code.
    targets = link_targets(on_disk)
    for p in records:
        if p.name not in targets:
            rejects.append(f"[uncovered-record] {p.name} — decisions/ carries this record and the "
                           f"index does not link it")

    #: INDEPENDENT ASSERTION 2 — git history. A removed record is not on disk, so the filesystem walk
    #: above can never see it; the one job the retired table has is to catch a pointer that still
    #: names it, and the hand-written table missed a removal for that exact reason.
    for r in removed:
        if r["name"] not in on_disk:
            rejects.append(f"[uncovered-retired] {r['name']} — git records this record as removed "
                           f"({r['date']}, {r['commit']}) and the index does not name it")
    return rejects, counts


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# self-test — one mutant per reject class, over a real git fixture
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def _fixture(root: pathlib.Path) -> None:
    """A small repository shaped like this one: records with and without a state, and a removal."""
    (root / "decisions").mkdir(parents=True)
    g = ["git", "-C", str(root), "-c", "user.name=self-test", "-c", "user.email=self@test",
         "-c", "commit.gpgsign=false"]
    subprocess.run(["git", "init", "-q", str(root)], check=True, capture_output=True)
    (root / "decisions" / "RULED-2026-01-01_alpha.md").write_text(
        "# RULED — alpha\n\n**Status: RULED BY THE OPERATOR.** Supersedes `PROPOSED-2026-01-02_beta.md`.\n",
        encoding="utf-8")
    (root / "decisions" / "PROPOSED-2026-01-02_beta.md").write_text(
        "# PROPOSED — beta\n\nNo status line anywhere, so its state is unknown.\n", encoding="utf-8")
    (root / "decisions" / "PROPOSED-2026-01-03_gamma.md").write_text(
        "# PROPOSED — gamma\n\n**Status: SUPERSEDED 2026-01-04 by `RULED-2026-01-01_alpha.md`.**\n",
        encoding="utf-8")
    (root / "notes.md").write_text("see `PROPOSED-2026-01-02_beta.md`\n", encoding="utf-8")
    subprocess.run(g + ["add", "-A"], check=True, capture_output=True)
    subprocess.run(g + ["commit", "-q", "-m", "fixture: three records"], check=True, capture_output=True)
    subprocess.run(g + ["rm", "-q", "decisions/PROPOSED-2026-01-03_gamma.md"],
                   check=True, capture_output=True)
    subprocess.run(g + ["commit", "-q", "-m", "retire gamma: carried by alpha"],
                   check=True, capture_output=True)


def self_test() -> int:
    checks = 0
    failures: list[str] = []

    def expect(cond, msg):
        nonlocal checks
        checks += 1
        if not cond:
            failures.append(msg)

    with tempfile.TemporaryDirectory() as tmp:
        fake = pathlib.Path(tmp) / "repo"
        try:
            _fixture(fake)
        except (OSError, subprocess.SubprocessError) as exc:
            print(f"COULD NOT RUN: the self-test needs a working git ({exc})", file=sys.stderr)
            return 2

        idx = index_path(fake)
        idx.write_text(render(fake), encoding="utf-8")
        rejects, counts = check(fake)
        expect(rejects == [], f"a freshly written index must be clean, got {rejects[:3]}")
        expect(counts["records"] == 2 and counts["removed"] == 1,
               f"the fixture must offer 2 live and 1 removed record, got {counts}")
        text = idx.read_text(encoding="utf-8")
        expect("**UNKNOWN**" in text,
               "a record with no state declaration must be rendered as an explicit UNKNOWN")
        expect("PROPOSED-2026-01-03_gamma.md" in text,
               "a record git records as removed must be named on the page")
        clean = text

        # stale-index
        idx.write_text(clean.replace("# decisions/ — the record", "# EDITED BY HAND"), encoding="utf-8")
        expect(any(r.startswith("[stale-index]") for r in check(fake)[0]),
               "a hand-edited index must reject as stale-index")

        # missing-index
        idx.unlink()
        expect(any(r.startswith("[missing-index]") for r in check(fake)[0]),
               "a deleted index must reject as missing-index")
        idx.write_text(clean, encoding="utf-8")

        # uncovered-record, the live failure mode: a record is added and the index is not regenerated.
        new = decisions_dir(fake) / "PROPOSED-2026-01-05_delta.md"
        new.write_text("# PROPOSED — delta\n\n**Status: PROPOSED.**\n", encoding="utf-8")
        expect(any(r.startswith("[uncovered-record]") for r in check(fake)[0]),
               "a record on disk and absent from the index must reject as uncovered-record")
        # and the one only the independent walk can see: regenerate, then cut the row out.
        idx.write_text(render(fake), encoding="utf-8")
        expect(check(fake)[0] == [], "regenerating over a new record must return to clean")
        gutted = [ln for ln in idx.read_text(encoding="utf-8").splitlines()
                  if "PROPOSED-2026-01-05_delta.md" not in ln]
        idx.write_text("\n".join(gutted) + "\n", encoding="utf-8")
        expect(any(r.startswith("[uncovered-record]") for r in check(fake)[0]),
               "a row cut out of the index must reject as uncovered-record, not only as stale-index")
        new.unlink()
        idx.write_text(render(fake), encoding="utf-8")
        expect(check(fake)[0] == [], "removing the mutant record and regenerating must be clean")

        # uncovered-retired — the row for a record that exists ONLY in git history.
        gutted = [ln for ln in idx.read_text(encoding="utf-8").splitlines()
                  if "PROPOSED-2026-01-03_gamma.md" not in ln]
        idx.write_text("\n".join(gutted) + "\n", encoding="utf-8")
        r = check(fake)[0]
        expect(any(x.startswith("[uncovered-retired]") for x in r),
               "a removed record the index stops naming must reject as uncovered-retired")
        idx.write_text(render(fake), encoding="utf-8")
        expect(check(fake)[0] == [], "restoring every mutant must return to clean")

    if failures:
        for f in failures:
            print(f"  [SELF-TEST] {f}")
        print(f"FAIL: gen_decisions_index self-test — {len(failures)} of {checks} check(s) failed "
              f"over 4 reject class(es)")
        return 1
    print(f"PASS: gen_decisions_index self-test — {checks}/{checks} check(s) over 4 reject class(es): "
          f"missing-index · stale-index · uncovered-record · uncovered-retired")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the index is missing, stale, or omits a record")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args(argv)

    try:
        if a.self_test:
            return self_test()

        if a.check:
            rejects, counts = check(ROOT)
            for r in rejects[:40]:
                print(f"  {r}")
            if len(rejects) > 40:
                print(f"  … and {len(rejects) - 40} more")
            tail = (f"{counts['records']} record(s) on disk + {counts['removed']} removed per git "
                    f"history = {counts['records'] + counts['removed']} record(s) examined")
            if rejects:
                print(f"FAIL: gen_decisions_index — {len(rejects)} reject(s) over {tail}; run "
                      f"`python3 tools/gen_decisions_index.py` to regenerate")
                return 1
            print(f"PASS: gen_decisions_index — {tail}; the index is current and names every one")
            return 0

        index_path(ROOT).write_text(render(ROOT), encoding="utf-8")
        _, counts = check(ROOT)
        print(f"PASS: gen_decisions_index — wrote decisions/README.md: {counts['records']} record(s) "
              f"on disk + {counts['removed']} removed per git history = "
              f"{counts['records'] + counts['removed']} record(s) examined")
        return 0
    except CouldNotRun as exc:
        print(f"COULD NOT RUN: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
