#!/usr/bin/env python3
"""gen_manual_index.py — the reference manual's index, READ off the manual instead of typed.

WHAT WAS WRONG WITH THE HAND-WRITTEN ONE. `reference_manual/README.md` was 173 lines in which a
person typed every page name, every status and every count, and measured 2026-10-04 it was the
largest single source of false statements in this repository:

  * "only 3 of 19 [canons] do anything today" — `canon_library.md` said "20 defined, 20 described,
    17 implemented" and `check_canon_documented.py` run that day said "defined 21 described 20
    implemented 18". THREE numbers for one fact, and the one in the index was the furthest out.
  * "20 notions, 119 terms" and "It is green: 20 of 20" — `mac_vocabulary.yaml` carries 24 notions
    holding 144 terms, and four of those notions have no chapter at all.
  * nine of the manual's pages were MISSING from the index entirely, among them the only two canons
    the runtime SHIPS — `resolve_by_register`, which every name resolution in every bundle goes
    through, and `enum_from_register` — while twelve reference-only canons were listed.
  * two live generated artifacts, `column_bench.html` and `grammar_map.html`, were linked from no
    page in the directory, and the 56-page generated key reference under `keys/` was unreachable.
  * 19 pattern pages were marked "written" while all 19 carry `status: prototype` themselves.

NO NUMBER ON THE PAGE THIS WRITES IS TYPED HERE. The page list is a filesystem walk. Each page's
status is that page's OWN `status:` frontmatter, quoted. The canon counts come from the three lists
`check_canon_documented.py` compares — `mac_vocabulary.yaml#canon`, `reference_manual/canon/*.md` and
`mac_runtime.canon.IMPLEMENTED`. The vocabulary counts come from `mac_vocabulary.yaml` and from
`gen_vocabulary_terms.py`'s own block markers, imported rather than restated.

AND WHAT CANNOT BE READ IS ON THE PAGE. Measured 2026-10-04, five files of the manual yield no
status at all — two markdown pages carry no frontmatter, two are HTML artifacts and one is a YAML
declaration — and one more carries frontmatter that is not valid YAML, so its `status:` line is read
literally and SAID to have been read that way. All six are listed as DECLARED UNKNOWNS with the
reason, because an index that quietly guesses is the thing this replaces.

THE CHECK DOES NOT ONLY RE-RENDER. Byte-comparing the page against a fresh render catches a page
someone edited and CANNOT catch this renderer dropping a page — which is the measured defect it
exists to prevent: `gen_schema_shapes.py --check` reports `shape_reference.md` current while the
page omits a key the schema has carried since 2026-09-28, because the comparator and the renderer
are the same code. So `--check` also walks the filesystem and asserts, against the LINK TARGETS
parsed out of the page on disk, that every page appears in the index — and that every page of the
`keys/` subtree is reachable through the sub-index this page delegates to. Different questions,
different evidence, so they cannot agree by construction.

    python3 tools/gen_manual_index.py                 # write reference_manual/README.md
    python3 tools/gen_manual_index.py --check         # exit 1 if stale or incomplete
    python3 tools/gen_manual_index.py --self-test     # one mutant per reject class + a clean fixture
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import shutil
import sys
import tempfile

try:
    import yaml
except ImportError:                                           # pragma: no cover
    print("COULD NOT RUN: pyyaml is not installed", file=sys.stderr)
    raise SystemExit(2)

SELF = pathlib.Path(__file__).resolve()
TOOLS = SELF.parent
ROOT = TOOLS.parent

#: The files of the manual a reader can open. `.yaml` is here because the manual carries one —
#: `column_effects.yaml` — and leaving a whole file out of a completeness claim is the defect.
PAGE_SUFFIXES = (".md", ".html", ".yaml")

BANNER = "<!-- GENERATED by tools/gen_manual_index.py — do not edit; regenerate. -->"
LINK_RE = re.compile(r"\]\(([^)\s]+)\)")
#: A GENERATOR ATTRIBUTION, not merely a mention. `tools/gen_x.py` has to appear on a line that also
#: says GENERATED / generated by / generated_by — which is how every generated page in this manual
#: signs itself. Matching the bare path instead credited `column_effects.yaml` to the generator that
#: READS it ("CONSUMED BY tools/gen_column_bench.py"), i.e. it invented a false statement of exactly
#: the kind this page exists to delete.
GEN_RE = re.compile(r"^(?=.*(?:GENERATED|generated by|generated_by)).*?tools/(gen_[a-z0-9_]+)\.py",
                    re.M)
H1_RE = re.compile(r"^#\s+(.*)$", re.M)
HTML_TITLE_RE = re.compile(r"<title>(.*?)</title>", re.S)
STATUS_LINE_RE = re.compile(r"^status:\s*(.*)$", re.M)
#: No leading `\b`: `v0.1.12` has no word boundary between `v` and `0`, so a `\b` anchored pattern
#: found 2 of the 5 versions `shape_reference.md` actually names.
SEMVER_RE = re.compile(r"(?<![\d.])\d+\.\d+\.\d+(?![\d.])")
FINDING_RE = re.compile(r"^##\s+(F\d+\s+—.*)$", re.M)

CELL_WIDTH = 104          # a presentation choice, not a fact about the manual


class CouldNotRun(Exception):
    """A source this index is DERIVED FROM is unreadable. Exit 2 — never a verdict."""


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# where things are, derived from one root so the self-test fixture is a real repository
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def manual_dir(root: pathlib.Path) -> pathlib.Path:
    return root / "reference_manual"


def index_path(root: pathlib.Path) -> pathlib.Path:
    return manual_dir(root) / "README.md"


def keys_index_path(root: pathlib.Path) -> pathlib.Path:
    return manual_dir(root) / "keys" / "README.md"


def manual_files(root: pathlib.Path) -> list[pathlib.Path]:
    """Every openable file of the manual, keys/ included. Sorted, so the page is deterministic."""
    return sorted(p for p in manual_dir(root).rglob("*")
                  if p.is_file() and p.suffix in PAGE_SUFFIXES)


def under_keys(root: pathlib.Path, path: pathlib.Path) -> bool:
    return "keys" in path.relative_to(manual_dir(root)).parts


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# reading what each page says about itself
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def front_matter(text: str) -> tuple[dict | None, str | None]:
    """(parsed frontmatter or None, raw frontmatter block or None)."""
    if not text.startswith("---"):
        return None, None
    end = text.find("\n---", 3)
    if end < 0:
        return None, None
    block = text[text.index("\n") + 1:end]
    try:
        parsed = yaml.safe_load(block)
    except yaml.YAMLError:
        return None, block
    return (parsed if isinstance(parsed, dict) else None), block


def status_from_block(block: str) -> str | None:
    """`status:` read as a literal line, for frontmatter YAML cannot parse.

    Not a guess: the line IS the declaration. The page records that it was read this way, so a
    reader can tell a parsed status from a scraped one.
    """
    m = STATUS_LINE_RE.search(block)
    if not m:
        return None
    out = [m.group(1)]
    for line in block[m.end():].splitlines()[1:]:
        if re.match(r"^\S", line):
            break
        out.append(line.strip())
    return " ".join(x for x in out if x).strip() or None


def describe(path: pathlib.Path, base: pathlib.Path) -> dict:
    """One page, as the page itself declares it. `how` records WHERE the status came from."""
    text = path.read_text(encoding="utf-8", errors="replace")
    title = status = None
    how = "absent"

    if path.suffix == ".md":
        parsed, block = front_matter(text)
        if parsed is not None:
            title = parsed.get("title")
            raw = parsed.get("status")
            if raw is None:
                how = "absent (its frontmatter carries no status: key)"
            else:
                status, how = str(raw), "frontmatter"
        elif block is not None:
            status = status_from_block(block)
            how = ("frontmatter-line (its frontmatter is not valid YAML, so the status: line was "
                   "read literally)") if status else \
                  "unreadable (its frontmatter is not valid YAML and carries no status: line)"
        else:
            how = "absent (the page carries no frontmatter)"
        if not title:
            m = H1_RE.search(text)
            title = m.group(1).strip() if m else None
    elif path.suffix == ".html":
        m = HTML_TITLE_RE.search(text)
        title = m.group(1).strip() if m else None
        how = "absent (an HTML artifact carries no frontmatter)"
    else:
        first = next((ln for ln in text.splitlines() if ln.startswith("#")), "")
        title = first.lstrip("# ").strip() or None
        how = "absent (a YAML declaration carries no frontmatter)"

    return {"rel": path.relative_to(base).as_posix(), "title": title, "status": status, "how": how,
            "generators": sorted(set(GEN_RE.findall(text))),
            "lines": len(text.splitlines())}


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# reading the declarations the gates already read
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def canon_lists(root: pathlib.Path) -> dict:
    """The THREE canon lists `check_canon_documented.py` compares, from the same three sources."""
    vocab_file = root / "mac_vocabulary.yaml"
    pages_dir = manual_dir(root) / "canon"
    if not vocab_file.is_file() or not pages_dir.is_dir():
        raise CouldNotRun(f"need {vocab_file.name} and {pages_dir}")
    block = (yaml.safe_load(vocab_file.read_text(encoding="utf-8")) or {}).get("canon") or {}
    # `terms:` is the vocabulary's key; `members:` is the older spelling, read the same way the
    # canon gate reads it — one wrong key there once reported 19 defined canons as 0.
    defined = block.get("terms") if block.get("terms") is not None else (block.get("members") or {})
    described = {p.stem for p in pages_dir.glob("*.md")}

    sys.path.insert(0, str(TOOLS))
    try:
        import _neighbours
        _neighbours.ensure_runtime_on_path()
        from mac_runtime.canon import IMPLEMENTED
    except ImportError as exc:
        # THE SAME REFUSAL `check_canon_documented.py` MAKES. "Implemented" is the number the old
        # index got most wrong ("only 3 of 19 do anything today"); rendering the page without it
        # would swap a wrong number for a silent omission, and a page whose content depended on
        # whether the runtime happened to be reachable could never be byte-compared by a gate.
        raise CouldNotRun(f"mac_runtime.canon is not importable ({exc}). The implemented list is the "
                          f"one source this index cannot do without; set $MAC_RUNTIME_SRC.")
    return {"defined": dict(defined), "described": described,
            "honoured": {name.rsplit(".", 1)[-1] for name in IMPLEMENTED}}


def vocabulary_lists(root: pathlib.Path) -> dict:
    """Notions, their terms, and WHICH PAGE documents each.

    A notion is a top-level entry of `mac_vocabulary.yaml` that declares a `kind:`. Measured on this
    vocabulary that is exactly the set `gen_vocabulary_terms.py` renders, and it is inclusive rather
    than a restated list of kinds: a NEW kind shows up here instead of being silently dropped. The
    notion-to-page map is read from that generator's own block markers, imported not restated.
    """
    sys.path.insert(0, str(TOOLS))
    try:
        import gen_vocabulary_terms as gvt
    except ImportError as exc:                                 # pragma: no cover
        raise CouldNotRun(f"gen_vocabulary_terms is not importable ({exc})")
    vocab_file = root / "mac_vocabulary.yaml"
    if not vocab_file.is_file():
        raise CouldNotRun(f"need {vocab_file}")
    vocab = yaml.safe_load(vocab_file.read_text(encoding="utf-8")) or {}
    notions = {k: v for k, v in vocab.items() if isinstance(v, dict) and v.get("kind")}
    where: dict[str, list[str]] = {}
    for page in sorted(manual_dir(root).glob("*.md")):
        for m in gvt.BLOCK.finditer(page.read_text(encoding="utf-8", errors="replace")):
            where.setdefault(m.group("notion"), []).append(page.name)
    return {"notions": notions, "where": where}


def suite_visible_generators(root: pathlib.Path) -> set[str]:
    """Which gen_*.py a `check_*.py` delegates to — i.e. which ones the suite can see at all.

    `run_framework_gates.sh` discovers gates by globbing `check_*.py`, so a generator's own
    `--check` is invisible to the suite unless some checker imports it. Read, not assumed.
    """
    seen: set[str] = set()
    for p in sorted((root / "tools").glob("check_*.py")):
        text = p.read_text(encoding="utf-8", errors="replace")
        seen.update(m.group(1) for m in re.finditer(r"import\s+(gen_[a-z0-9_]+)", text))
    return seen


def findings(root: pathlib.Path) -> list[str]:
    f = manual_dir(root) / "FINDINGS.md"
    if not f.is_file():
        return []
    return [m.group(1).strip() for m in FINDING_RE.finditer(f.read_text(encoding="utf-8"))]


def shape_version_note(root: pathlib.Path, schema_version) -> str:
    """What `shape_reference.md` NAMES, measured. The index used to call its shapes always current."""
    p = manual_dir(root) / "shape_reference.md"
    if not p.is_file() or not schema_version:
        return ""
    found = sorted(set(SEMVER_RE.findall(p.read_text(encoding="utf-8", errors="replace"))),
                   key=lambda v: tuple(int(x) for x in v.split(".")))
    if not found:
        return "`shape_reference.md` names no schema version."
    named = ", ".join(f"`{v}`" for v in found)
    if schema_version in found:
        return f"`shape_reference.md` names {named}, the current one among them."
    return (f"`shape_reference.md` names {named} and **not** `{schema_version}`: the block "
            f"`gen_schema_shapes.py` writes is held current by its own `--check`, the prose around "
            f"it is not held by anything.")


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# rendering
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def cell(text, width: int = CELL_WIDTH) -> str:
    if text is None:
        return "—"
    s = re.sub(r"\s+", " ", str(text)).strip()
    s = re.sub(r"\s+#\s.*$", "", s)            # a YAML trailing comment, when the line was read raw
    if len(s) > width:
        s = s[:width - 1].rstrip() + "…"
    return s.replace("|", "\\|") or "—"


def gen_cell(page: dict, visible: set[str]) -> str:
    if not page["generators"]:
        return "hand-written"
    return " · ".join(f"`{g}`" + ("" if g in visible else " **(no `check_*.py`)**")
                      for g in page["generators"])


def page_table(pages: list[dict], visible: set[str]) -> list[str]:
    rows = ["| page | title | `status:` as the page itself declares it | generated by |",
            "|---|---|---|---|"]
    for p in pages:
        rows.append(f"| [`{p['rel']}`]({p['rel']}) | {cell(p['title'], 72)} | {cell(p['status'])} "
                    f"| {gen_cell(p, visible)} |")
    return rows


def render(root: pathlib.Path) -> str:
    manual = manual_dir(root)
    files = manual_files(root)
    if not files:
        raise CouldNotRun(f"{manual} holds no .md/.html/.yaml file")

    me = index_path(root)
    keys_files = [p for p in files if under_keys(root, p)]
    described = [describe(p, manual) for p in files
                 if not under_keys(root, p) and p != me]

    root_pages = [p for p in described if "/" not in p["rel"] and p["rel"].endswith(".md")]
    canon_pages = {p["rel"][len("canon/"):-len(".md")]: p
                   for p in described if p["rel"].startswith("canon/")}
    pattern_pages = [p for p in described if p["rel"].startswith("patterns/")]
    artifacts = [p for p in described if not p["rel"].endswith(".md")]

    #: EVERY OTHER SUBDIRECTORY, DISCOVERED RATHER THAN LISTED. The four groups above are the only ones
    #: this renderer knew, and `canon/` · `patterns/` · `keys/` were spelled out — so when
    #: meaning-as-code homed thirteen pages into `specification/` · `guides/` · `discipline/`
    #: (`guardrails/document_home.yaml`), they belonged to NO group and were simply not rendered. Four
    #: of them vanished from the index entirely; the nine without frontmatter showed up only in the
    #: "declared unknowns" list, which made the omission look like a status problem. The gate caught it
    #: because its coverage walk reads the filesystem and not this renderer — which is the whole reason
    #: that assertion is independent.
    #:
    #: GROUPED BY DIRECTORY AND DISCOVERED, so the NEXT directory indexes itself on the day it appears.
    KNOWN = ("canon/", "patterns/", "keys/")
    subdirs: dict[str, list[dict]] = {}
    for d in described:
        rel = d["rel"]
        if "/" not in rel or not rel.endswith(".md") or rel.startswith(KNOWN):
            continue
        subdirs.setdefault(rel.split("/", 1)[0], []).append(d)
    subdir_pages = [d for group in subdirs.values() for d in group]

    canon = canon_lists(root)
    vocab = vocabulary_lists(root)
    visible = suite_visible_generators(root)
    schema_version = json.loads((root / "mac.schema.json").read_text(encoding="utf-8")).get("version")

    keys_rel = sorted(p.relative_to(manual).as_posix() for p in keys_files)
    keys_other = [k for k in keys_rel if k != "keys/README.md"]
    has_keys_index = keys_index_path(root).is_file()

    unknowns = [p for p in described if p["status"] is None]
    raw_read = [p for p in described if p["how"].startswith("frontmatter-line")]

    histogram: dict[str, int] = {}
    for p in described:
        k = cell(p["status"], 44) if p["status"] else "— (no status declared)"
        histogram[k] = histogram.get(k, 0) + 1

    L: list[str] = []
    A = L.append

    A("---")
    A("title: The Reference Manual — the index")
    A("part_of: reference_manual")
    A(f"status: GENERATED by tools/gen_manual_index.py from the manual itself — "
      f"{len(described) + 1} file(s) outside keys/ and {len(keys_rel)} under it. Every page name, "
      f"status and count below is read from a file; none is typed. Held by "
      f"tools/check_manual_index.py.")
    A("scope: GENERIC — this index names the manual's own files and the declarations they are derived "
      "from. No business domain, warehouse or vendor appears here.")
    A("---")
    A("")
    A(BANNER)
    A("")
    A("# Modeling Meaning as Code — The Reference Manual")
    A("")
    A("> **The book this wants to be.** Kernighan & Ritchie did not just list C's keywords; they")
    A("> taught the *idioms* — \"here is the shape of problem you will meet, here is how you say it in")
    A("> this language.\" No such book exists for **modeling meaning**. The relational world has Codd")
    A("> and the normal forms; the warehouse world has Kimball's dimensional catalogue; the")
    A("> semantic-web world has RDF/OWL. Each is a mature pattern language for *one* target. None is a")
    A("> pattern language for capturing meaning **once**, tool-neutrally, readable by a person, a")
    A("> machine, and an AI agent alike. This manual is the attempt.")
    A("")
    A("**How to read this index, and why it looks like this.** Every row below is read from the file")
    A("it names. The `status:` column is that page's OWN frontmatter, quoted — not a judgement made")
    A("here, so a page that calls itself a prototype is listed as a prototype. The counts are read")
    A("from the declarations the gates already read: `mac.schema.json`, `mac_vocabulary.yaml`, and the")
    A("runtime's implemented-canon set. Nothing on this page is typed by a person, because the")
    A("hand-written index it replaces carried three different numbers for one canon count and omitted")
    A("nine of its own pages. Pages appear in filename order within each group: no reading order is")
    A("asserted that a file does not declare. This file is `README.md` and is not listed among them.")
    A("")

    A("## What is on disk")
    A("")
    A("| where | openable files | what indexes them |")
    A("|---|---|---|")
    A(f"| `reference_manual/` (markdown, top level) | {len(root_pages)} | this page, below |")
    A(f"| `reference_manual/canon/` | {len(canon_pages)} | this page, below, beside the canon "
      f"vocabulary and the runtime |")
    A(f"| `reference_manual/patterns/` | {len(pattern_pages)} | this page, below |")
    for d in sorted(subdirs):
        A(f"| `reference_manual/{d}/` | {len(subdirs[d])} | this page, below |")
    A(f"| artifacts that are not markdown | {len(artifacts)} | this page, below |")
    A(f"| `reference_manual/keys/` | {len(keys_rel)} | its own generated index, "
      f"[`keys/README.md`](keys/README.md)" + ("" if has_keys_index else " — **ABSENT**") + " |")
    A(f"| **total** | **{len(files)}** | this index is one of them, and is counted but not listed |")
    A("")
    A("What the manual says about its own pages, counted — each key is a page's own `status:`, so a")
    A("page that calls itself a prototype is counted as a prototype:")
    A("")
    ordered = sorted(histogram.items(), key=lambda kv: (-kv[1], kv[0]))
    shared = [(s, n) for s, n in ordered if n > 1]
    singles = [(s, n) for s, n in ordered if n == 1]
    for s, n in shared:
        A(f"* **{n}** × {s}")
    if singles:
        A(f"* **{len(singles)}** further file(s) each declare a status of their own, one page each — "
          f"quoted in full in the tables below.")
    A("")

    A("## Chapters and standing pages")
    A("")
    L.extend(page_table(root_pages, visible))
    A("")

    #: One section per discovered directory, in name order — see the KNOWN/subdirs note above.
    for d in sorted(subdirs):
        A(f"## `{d}/` — {len(subdirs[d])} page(s)")
        A("")
        L.extend(page_table(sorted(subdirs[d], key=lambda x: x["rel"]), visible))
        A("")

    A(f"A generator marked **(no `check_*.py`)** writes a page that no gate in the suite runs. "
      f"`tools/run_framework_gates.sh` discovers gates by globbing `check_*.py`, so a `gen_*.py "
      f"--check` is invisible to it unless a checker delegates; measured over `tools/check_*.py`, "
      f"{len(visible)} generator(s) are delegated to "
      f"({', '.join('`' + g + '`' for g in sorted(visible)) or 'none'}).")
    A("")
    A(f"`mac.schema.json` declares version **{schema_version}**. {shape_version_note(root, schema_version)}")
    A("")

    notions, where = vocab["notions"], vocab["where"]
    terms_total = sum(len(v.get("terms") or v.get("members") or {}) for v in notions.values())
    documented = sorted(n for n in notions if n in where)
    undocumented = sorted(n for n in notions if n not in where)
    A("## The vocabulary reference")
    A("")
    A(f"**Every term MAC defines, and the page that documents it.** `mac_vocabulary.yaml` declares "
      f"**{len(notions)} notion(s)** holding **{terms_total} term(s)**. **{len(documented)}** notion(s) "
      f"have a chapter; **{len(undocumented)}** do not. The definitions inside each chapter are "
      f"rendered from the vocabulary by `tools/gen_vocabulary_terms.py`, so they cannot drift; which "
      f"notion sits on which page is read from that generator's own block markers.")
    A("")
    A("| notion | kind | terms | closed | documented in |")
    A("|---|---|---|---|---|")
    for n in sorted(notions):
        spec = notions[n]
        entries = spec.get("terms") or spec.get("members") or {}
        pages = where.get(n)
        loc = " · ".join(f"[`{p}`]({p})" for p in pages) if pages else "**— no chapter**"
        A(f"| `mac.{n}` | {cell(spec.get('kind'), 20)} | {len(entries)} | "
          f"{'yes' if spec.get('closed') else 'no'} | {loc} |")
    A("")
    if undocumented:
        A(f"The {len(undocumented)} notion(s) with no chapter, which `gen_vocabulary_terms.py --check` "
          f"prints as UNDOCUMENTED: " + ", ".join(f"`mac.{n}`" for n in undocumented) + ".")
        A("")
    A("Where a constellation already has a **pattern**, these pages link to the pattern rather than")
    A("restate it. The pattern is canonical.")
    A("")

    defined, described_c, honoured = canon["defined"], canon["described"], canon["honoured"]
    A("## The canon library")
    A("")
    A(f"The deterministic behaviour a concept's `realized_by:` names. A canon exists in three places "
      f"and `tools/check_canon_documented.py` compares them: **{len(defined)} defined** in "
      f"`mac_vocabulary.yaml` under `canon`, **{len(described_c)} described** by a page under "
      f"`canon/`, **{len(honoured)} implemented** in the runtime's implemented-canon set. The three "
      f"middle columns below ARE those three lists; the last is the page's own frontmatter.")
    A("")
    A("| canon | defined | page | implemented | `status:` as the page declares it |")
    A("|---|---|---|---|---|")
    for name in sorted(set(defined) | described_c | honoured):
        page = canon_pages.get(name)
        link = f"[`canon/{name}.md`](canon/{name}.md)" if page else "**— none**"
        A(f"| `mac.canon.{name}` | {'yes' if name in defined else '**no**'} | {link} "
          f"| {'yes' if name in honoured else 'no'} | {cell(page['status'] if page else None)} |")
    A("")
    disagree = sorted(n for n in described_c & honoured
                      if re.match(r"NOT IMPLEMENTED", str(canon_pages[n]["status"] or ""), re.I))
    if disagree:
        A(f"**{len(disagree)} page(s) call themselves not implemented while the runtime lists them as "
          f"implemented:** " + ", ".join(f"`{n}`" for n in disagree) + ". Both lists are shown as they "
          f"are read; reconciling them is a change to one of them, not to this index.")
        A("")

    A("## Patterns (worked entries)")
    A("")
    A(f"{len(pattern_pages)} page(s) under `patterns/`, each at the status it declares for itself.")
    A("")
    L.extend(page_table(pattern_pages, visible))
    A("")

    A("## The generated key reference")
    A("")
    if has_keys_index:
        A(f"[`keys/README.md`](keys/README.md) indexes **{len(keys_other)}** further page(s) — one per "
          f"LEVEL of a concept file and one per vocabulary notion, written by "
          f"`tools/gen_key_reference.py` from `mac.schema.json` and `mac_vocabulary.yaml`. They are not "
          f"repeated here, because that sub-index is generated too; `tools/check_manual_index.py` "
          f"asserts from the filesystem that every one of them is reachable through it.")
    else:
        A(f"**{len(keys_other)} page(s) exist under `keys/` and there is no `keys/README.md` to index "
          f"them.** Run `python3 tools/gen_key_reference.py`.")
    A("")

    A("## Artifacts that are not markdown")
    A("")
    A("Generated, live, and — until this index was generated — linked from no page in the directory.")
    A("")
    A("| artifact | title | lines | generated by |")
    A("|---|---|---|---|")
    for p in artifacts:
        A(f"| [`{p['rel']}`]({p['rel']}) | {cell(p['title'], 72)} | {p['lines']} "
          f"| {gen_cell(p, visible)} |")
    A("")

    fs = findings(root)
    A("## Findings, and how this manual is written")
    A("")
    A(f"[`FINDINGS.md`](FINDINGS.md) records the candidate framework changes a pattern surfaced but "
      f"did not enact, for the maintainer's decision. It carries **{len(fs)}**:")
    A("")
    for f in fs:
        A(f"* {f}")
    A("")
    A("[`AUTHORING.md`](AUTHORING.md) is the manual's authoring constitution — the rules the manual")
    A("holds itself to, including the one this index exists to satisfy: publish coverage, never a")
    A("completeness claim. A reference manual for frameworks needs its own framework.")
    A("")

    A("## Declared unknowns — what this index could not read")
    A("")
    if unknowns:
        A(f"**{len(unknowns)} of {len(described)}** file(s) outside `keys/` yield no `status:`. Each is "
          f"listed with the reason, because a guess here is worse than a gap.")
        A("")
        A("| file | why there is no status |")
        A("|---|---|")
        for p in unknowns:
            A(f"| [`{p['rel']}`]({p['rel']}) | {cell(p['how'])} |")
    else:
        A(f"None — all {len(described)} file(s) outside `keys/` declare a readable `status:`.")
    A("")
    if raw_read:
        A(f"**{len(raw_read)}** page(s) carry frontmatter that is not valid YAML; the `status:` line "
          f"was read literally instead, which is a declaration and not an inference: "
          + ", ".join(f"[`{p['rel']}`]({p['rel']})" for p in raw_read) + ".")
        A("")
    spec = root / "CONCEPT_SPEC.md"
    if spec.is_file():
        s = describe(spec, root)
        A(f"`../CONCEPT_SPEC.md` **is still present** ({s['lines']} lines). The hand-written index said")
        A(f"the shape reference \"supersedes the retired `../CONCEPT_SPEC.md`\", which reads as removed.")
        A(f"The file's own status: {cell(s['status'], 150)}")
        A("")

    A("## What holds this index")
    A("")
    A("`python3 tools/gen_manual_index.py` writes this page. `python3 tools/check_manual_index.py` —")
    A("which `tools/run_framework_gates.sh` runs, because the suite globs `check_*.py` — rejects it on")
    A("four separate grounds: the index is **missing**; the index is **stale** against a fresh render;")
    A("a page **exists on disk and this index does not link it**; a page of the `keys/` subtree is")
    A("**not reachable** through the sub-index this page delegates to. The last two are asserted from a")
    A("filesystem walk against the link targets parsed out of this page as written, not from the")
    A("renderer's own model — so a renderer that silently drops a row is caught by evidence that")
    A("cannot agree with it.")
    A("")
    return "\n".join(L) + "\n"


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# the check — two kinds of question, four rejects
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def link_targets(text: str) -> set[str]:
    """Every relative link target on a page, as written. Parsed from the PAGE, not from the model."""
    out = set()
    for raw in LINK_RE.findall(text):
        if "://" in raw or raw.startswith(("#", "mailto:")):
            continue
        out.add(raw.split("#", 1)[0].strip("`"))
    return out


def check(root: pathlib.Path) -> tuple[list[str], dict]:
    manual = manual_dir(root)
    index = index_path(root)
    files = manual_files(root)
    counts = {"existing": len(files), "listed": 0, "keys": 0}
    rejects: list[str] = []

    if not index.is_file():
        rejects.append(f"[missing-index] {index.relative_to(root)} — the manual has no index; run "
                       f"`python3 tools/gen_manual_index.py`")
        return rejects, counts

    on_disk = index.read_text(encoding="utf-8")
    if on_disk != render(root):
        rejects.append(f"[stale-index] {index.relative_to(root)} — the manual moved and the index did "
                       f"not; run `python3 tools/gen_manual_index.py`")

    #: THE INDEPENDENT ASSERTION. Everything above re-renders and byte-compares, which cannot catch
    #: THIS renderer dropping a page — the measured defect in `gen_schema_shapes.py --check`, where
    #: the comparator and the renderer are the same code and agree by construction. So: walk the
    #: filesystem and require every page to appear as a link target on the page AS WRITTEN.
    targets = link_targets(on_disk)
    for p in files:
        rel = p.relative_to(manual).as_posix()
        if rel == "README.md":
            continue                                  # this index itself: counted, never self-linked
        if under_keys(root, p):
            counts["keys"] += 1
            continue
        counts["listed"] += 1
        if rel not in targets:
            rejects.append(f"[uncovered-page] {rel} — the manual carries this page and the index does "
                           f"not link it")

    #: AND THE SUBTREE THIS INDEX DELEGATES. It claims `keys/README.md` indexes those pages; a
    #: completeness claim that hands off to another index is only true if that index is complete.
    keys_index = keys_index_path(root)
    if counts["keys"]:
        if not keys_index.is_file():
            rejects.append(f"[uncovered-keys-page] keys/README.md — {counts['keys']} page(s) under "
                           f"keys/ and no sub-index to reach them through")
        else:
            sub = link_targets(keys_index.read_text(encoding="utf-8"))
            for p in files:
                rel = p.relative_to(manual).as_posix()
                if not under_keys(root, p) or rel == "keys/README.md":
                    continue
                if rel[len("keys/"):] not in sub and rel not in sub:
                    rejects.append(f"[uncovered-keys-page] {rel} — this index delegates the keys/ "
                                   f"subtree to keys/README.md and that page does not link it")
    return rejects, counts


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# self-test — one mutant per reject class, plus a clean fixture that must pass
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def self_test() -> int:
    checks = 0
    failures: list[str] = []

    def expect(cond, msg):
        nonlocal checks
        checks += 1
        if not cond:
            failures.append(msg)

    with tempfile.TemporaryDirectory() as tmp:
        fake = pathlib.Path(tmp) / "repo"
        fake.mkdir()
        for name in ("mac_vocabulary.yaml", "mac.schema.json", "CONCEPT_SPEC.md"):
            if (ROOT / name).is_file():
                shutil.copy2(ROOT / name, fake / name)
        shutil.copytree(ROOT / "tools", fake / "tools",
                        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
        shutil.copytree(manual_dir(ROOT), manual_dir(fake))
        man = manual_dir(fake)
        idx = index_path(fake)

        idx.write_text(render(fake), encoding="utf-8")
        rejects, counts = check(fake)
        expect(rejects == [], f"a freshly written index must be clean, got {rejects[:3]}")
        expect(counts["existing"] > counts["listed"] > 0,
               "the denominator must count more files than it lists as rows — keys/ is delegated")
        clean = idx.read_text(encoding="utf-8")

        # stale-index
        idx.write_text(clean.replace("# Modeling Meaning as Code", "# EDITED BY HAND"), encoding="utf-8")
        expect(any(r.startswith("[stale-index]") for r in check(fake)[0]),
               "a hand-edited index must reject as stale-index")

        # missing-index
        idx.unlink()
        expect(any(r.startswith("[missing-index]") for r in check(fake)[0]),
               "a deleted index must reject as missing-index")
        idx.write_text(clean, encoding="utf-8")

        # uncovered-page, twice over. First the LIVE failure mode: a page is written and the index is
        # never regenerated. Then the one only the independent walk can see: the index IS regenerated
        # and the row is cut out of it afterwards — the renderer-drops-a-row defect.
        new = man / "patterns" / "zz_self_test_pattern.md"
        new.write_text("---\ntitle: self-test\nstatus: prototype\n---\n\n# self-test\n", encoding="utf-8")
        expect(any(r.startswith("[uncovered-page]") for r in check(fake)[0]),
               "a page on disk and absent from the index must reject as uncovered-page")
        idx.write_text(render(fake), encoding="utf-8")
        expect(check(fake)[0] == [], "regenerating over a new page must return to clean")
        gutted = [ln for ln in idx.read_text(encoding="utf-8").splitlines()
                  if "zz_self_test_pattern.md" not in ln]
        idx.write_text("\n".join(gutted) + "\n", encoding="utf-8")
        expect(any(r.startswith("[uncovered-page]") for r in check(fake)[0]),
               "a row cut out of the index must reject as uncovered-page, not only as stale-index")
        new.unlink()
        idx.write_text(render(fake), encoding="utf-8")
        expect(check(fake)[0] == [], "removing the mutant page and regenerating must be clean")

        # uncovered-keys-page — the delegated sub-index stops covering one of its own pages.
        sub = keys_index_path(fake)
        victim = next((p for p in sorted((man / "keys").rglob("*.md")) if p.name != "README.md"), None)
        if sub.is_file() and victim is not None:
            keep = sub.read_text(encoding="utf-8")
            inner = victim.relative_to(man / "keys").as_posix()
            sub.write_text("\n".join(ln for ln in keep.splitlines() if inner not in ln) + "\n",
                           encoding="utf-8")
            expect(any(r.startswith("[uncovered-keys-page]") for r in check(fake)[0]),
                   "a keys/ page the sub-index stops linking must reject as uncovered-keys-page")
            sub.write_text(keep, encoding="utf-8")
        else:
            expect(False, "the fixture carries no keys/ sub-index and page to mutate")

        idx.write_text(render(fake), encoding="utf-8")
        expect(check(fake)[0] == [], "restoring every mutant must return to clean")

    if failures:
        for f in failures:
            print(f"  [SELF-TEST] {f}")
        print(f"FAIL: gen_manual_index self-test — {len(failures)} of {checks} check(s) failed over "
              f"4 reject class(es)")
        return 1
    print(f"PASS: gen_manual_index self-test — {checks}/{checks} check(s) over 4 reject class(es): "
          f"missing-index · stale-index · uncovered-page · uncovered-keys-page")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the index is missing, stale, or omits a page the manual carries")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args(argv)

    try:
        if a.self_test:
            return self_test()

        if a.check:
            rejects, counts = check(ROOT)
            for r in rejects[:40]:
                print(f"  {r}")
            if len(rejects) > 40:
                print(f"  … and {len(rejects) - 40} more")
            tail = (f"{counts['listed']} page(s) listed + {counts['keys']} delegated to "
                    f"keys/README.md + 1 index = {counts['existing']} file(s) in reference_manual/")
            if rejects:
                print(f"FAIL: gen_manual_index — {len(rejects)} reject(s) over {tail}; run "
                      f"`python3 tools/gen_manual_index.py` to regenerate")
                return 1
            print(f"PASS: gen_manual_index — {tail}; the index is current and every page is covered")
            return 0

        index_path(ROOT).write_text(render(ROOT), encoding="utf-8")
        _, counts = check(ROOT)
        print(f"PASS: gen_manual_index — wrote reference_manual/README.md: {counts['listed']} page(s) "
              f"listed + {counts['keys']} delegated to keys/README.md + 1 index = "
              f"{counts['existing']} file(s) in reference_manual/")
        return 0
    except CouldNotRun as exc:
        print(f"COULD NOT RUN: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
