#!/usr/bin/env python3
"""gen_strategy.py — STRATEGY.md is GENERATED from guardrails/strategy.yaml, so it cannot narrate the past.

Operator, 2026-09-29: the strategy "needs to be formulated once properly, expressed in the docu",
and "the most affected is the documentation, which describes all possible states of the past". A
generated page has one state: the declaration's. Edit guardrails/strategy.yaml; `--check` fails when
the page on disk is not what the declaration renders.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "guardrails" / "strategy.yaml"
OUT = ROOT / "STRATEGY.md"


def _ref(r: str) -> str:
    repo, _, path = r.partition(":")
    if repo == "mac":
        return f"`{path}`"          # this repository: an owned-root path the dangling gate resolves
    if repo == "bundle":
        return f"`<bundle>/{path}`"
    home = {"kit": "mac-integration-kit", "platform": "mac-platform"}.get(repo, repo)
    return f"`{home}/{path}`"      # a sibling repository: UNLOCATED to the gate, never dangling


def render(doc: dict) -> str:
    L = []
    L.append("<!-- GENERATED by tools/gen_strategy.py from guardrails/strategy.yaml — do not edit; edit the declaration. -->")
    L.append(f"# The strategy — {doc.get('status', '')}\n")
    L.append(doc["aim"].strip() + "\n")
    L.append("**This page describes the present.** It is generated from `guardrails/strategy.yaml`, the one home of the "
             "strategy; `tools/check_strategy.py` holds every name on it to what exists and reports which rung a bundle "
             "has reached; the framework gate runner holds the rungs' gates on every delivery.\n")
    e = doc.get("essay") or {}
    for key, heading in (("opening", None), ("common", "The common ground"), ("mac", "What MAC is for"),
                         ("console", "What the console is for"), ("ladder", "The ladder, as a story")):
        if e.get(key):
            if heading:
                L.append(f"## {heading}\n")
            L.append(e[key].strip() + "\n")
    L.append("## Stop condition\n")
    L.append(doc["stop_condition"].strip() + "\n")
    L.append("## Principles, as declared\n")
    for p in doc["principles"]:
        L.append(f"- **{p['id']}** — {p['rule'].strip()}  \n  *Because:* {p['because'].strip()}")
    L.append("")
    L.append("## The rungs, as declared\n")
    L.append("| rung | what AI does | what a person does |")
    L.append("|---|---|---|")
    for r in doc["rungs"]:
        L.append(f"| {r['id']} · **{r['name']}** | {r['ai'].strip()} | {r['person'].strip()} |")
    L.append("")
    for r in doc["rungs"]:
        L.append(f"### {r['id']} · {r['name']}\n")
        L.append(f"**AI:** {r['ai'].strip()}  \n**Person:** {r['person'].strip()}\n")
        if r.get("tools"):
            L.append("- tools: " + ", ".join(_ref(x) for x in r["tools"]))
        if r.get("skills"):
            L.append("- skills: " + ", ".join(_ref(x) for x in r["skills"]))
        if r.get("artifacts"):
            L.append("- artifacts: " + ", ".join(_ref(x) for x in r["artifacts"]))
        if r.get("gates"):
            L.append("- gates: " + ", ".join(f"`{g}`" for g in r["gates"]))
        if r.get("console"):
            L.append("- console: " + ", ".join(f"`{c}`" for c in r["console"]))
        if r.get("enforced_by"):
            L.append("- enforced by: " + ", ".join(_ref(x) for x in r["enforced_by"]))
        if r.get("owed"):
            L.append(f"- **owed:** {r['owed'].strip()}")
        L.append("")
    d = doc["documentation"]
    L.append("## Documentation\n")
    L.append(d["rule"].strip() + "\n")
    L.append("Enforced by: " + ", ".join(_ref(x.split()[0]) for x in d["enforced_by"]) + ".  ")
    L.append(f"**Owed:** {d['owed'].strip()}\n")
    L.append("## Enforcement of this page\n")
    for e in doc["enforcement"]:
        tok, _, note = e.partition("#")
        L.append(f"- {_ref(tok.strip())}" + (f" — {note.strip()}" if note.strip() else ""))
    L.append("")
    return "\n".join(L)


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    doc = yaml.safe_load(SRC.read_text(encoding="utf-8"))
    text = render(doc)
    if "--check" in args:
        if not OUT.is_file():
            print(f"FAIL: gen_strategy — {OUT.name} is missing; run tools/gen_strategy.py")
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print(f"FAIL: gen_strategy — {OUT.name} is not what guardrails/strategy.yaml renders (hand edit, or the declaration moved); run tools/gen_strategy.py")
            return 1
        print(f"OK — {OUT.name} matches guardrails/strategy.yaml ({len(doc['rungs'])} rungs, {len(doc['principles'])} principles)")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.name}: {len(doc['rungs'])} rungs, {len(doc['principles'])} principles")
    return 0


if __name__ == "__main__":
    sys.exit(main())
