#!/usr/bin/env python3
"""gen_key_reference.py — one page per LEVEL of a concept file, every key, cross-linked.

WHAT A READER ASKED FOR, and could not get. Starting at `concept:`, which keywords may I write
underneath, what does each mean, which are required, what are the legal values of each, and what
sits one level further down. Then the same for the level below, and the level below that. The
answer existed only as `mac.schema.json`, which a person does not read, and as prose pages that
split one column map four ways across 1,619 lines.

WHY IT IS GENERATED AND NOT WRITTEN. `reference_manual/shape_reference.md` is the hand-written
answer to this question and it omits `rulings` — a key the schema has carried since 2026-09-28 —
while `gen_schema_shapes.py --check` reports the page current, because the comparator and the
renderer are the same code and agree by construction. A key reference restated by hand is a second
home for the schema and it is the home that rots. So every key, type, requirement and enum here is
READ from the schema, every term definition from `mac_vocabulary.yaml`, and every example is CUT
from a real concept in a worked bundle. Nothing on these pages is typed by a person.

AND WHAT IS UNEXPLAINED IS PART OF THE OUTPUT. Measured 2026-10-04 on schema 0.1.16: of 200 keys
a concept may write, 82 carry no description at all — `metadata.owner`, `concept.definition`,
`measure.type`, `measure.unit`. A generator that hid those would render a reference manual whose
silences look like completeness. Each is emitted as a named gap, counted on the level it sits on
and totalled in the index, and the place to fix one is the schema.

THE CHECK DOES NOT ONLY RE-RENDER. Byte-comparing a page against a fresh render catches a page
that drifted from the schema and CANNOT catch the renderer dropping a key — that is the exact
defect above. So `--check` also asserts, independently of the renderer, that every key the schema
admits appears on exactly one page. Two different questions, two different rejects.

    python3 tools/gen_key_reference.py                     # write the pages
    python3 tools/gen_key_reference.py --check             # exit 1 if stale, missing or uncovered
    python3 tools/gen_key_reference.py --self-test         # one mutant per reject class
"""
from __future__ import annotations

import argparse
import json
import pathlib
import shutil
import sys
import tempfile

try:
    import yaml
except ImportError:                                           # pragma: no cover
    print("COULD NOT RUN: pyyaml is not installed", file=sys.stderr)
    raise SystemExit(2)

SELF = pathlib.Path(__file__).resolve()
ROOT = SELF.parent.parent
OUT_DIR = ROOT / "reference_manual" / "keys"
VOCAB_DIR = OUT_DIR / "vocabulary"

#: THE FREE-KEY SEGMENT. A level whose names the author chooses — a column name, an axis name —
#: is `<name>` in the schema walk and `each` in a filename, because `<` and `>` are not portable
#: in a path and a reader has to be able to type the name of the page they want.
ANY = "<name>"
ANY_SLUG = "each"

BANNER = "<!-- GENERATED by tools/gen_key_reference.py — do not edit; regenerate. -->"


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# the two declarations
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def load(root: pathlib.Path):
    schema = json.loads((root / "mac.schema.json").read_text(encoding="utf-8"))
    vocab = yaml.safe_load((root / "mac_vocabulary.yaml").read_text(encoding="utf-8")) or {}
    return schema, vocab


def harvest_vocabulary(vocab: dict):
    """(notions, dotted) — the vocabulary indexed the way a concept actually spells a value.

    A concept writes `mac.concept.column.measure_type.flow`. The vocabulary files that under the
    notion `concept.column.measure_type` with the term `flow`, so the dotted name is `mac.` and
    the two joined. Indexing it this way means a NEW notion needs no change in this file.
    """
    notions: dict[str, dict] = {}
    dotted: dict[str, dict] = {}

    def walk(node, path=""):
        if not isinstance(node, dict):
            return
        terms = node.get("terms")
        if isinstance(terms, dict):
            entry = {"description": node.get("description"),
                     "closed": bool(node.get("closed")), "terms": {}}
            for term, body in terms.items():
                definition = body if isinstance(body, str) else (
                    (body or {}).get("definition") or (body or {}).get("description"))
                extra = ({k: v for k, v in body.items()
                          if k not in ("definition", "description")}
                         if isinstance(body, dict) else {})
                t = {"notion": path, "term": term, "definition": definition, "extra": extra}
                entry["terms"][term] = t
                dotted[f"mac.{path}.{term}"] = t
                dotted.setdefault(term, t)
            notions[path] = entry
        for k, v in node.items():
            if k != "terms":
                walk(v, f"{path}.{k}" if path else str(k))

    walk(vocab)
    return notions, dotted


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# the schema walk
# ──────────────────────────────────────────────────────────────────────────────────────────────────

class Walker:
    def __init__(self, schema: dict, dotted: dict):
        self.defs = schema["$defs"]
        self.dotted = dotted
        self.levels: dict[str, dict] = {}
        self.gaps: list[dict] = []

    def deref(self, node, guard: int = 0):
        while isinstance(node, dict) and guard < 16:
            guard += 1
            if "$ref" in node:
                node = self.defs.get(node["$ref"].split("/")[-1], {})
                continue
            if node.get("type") == "array" and "items" in node:
                node = node["items"]
                continue
            return node
        return node if isinstance(node, dict) else {}

    def shapes(self, node):
        """[(label, node)] — a key with several LEGAL shapes has several, not one.

        `grounding.sources[].columns` is why: it is a oneOf of a legacy flat list and the column
        map, and a reader shown only the first branch is shown the shape we are migrating away
        from.
        """
        n = self.deref(node)
        for comb in ("oneOf", "anyOf"):
            branches = n.get(comb)
            if isinstance(branches, list) and len(branches) > 1:
                out = []
                for i, sub in enumerate(branches):
                    d = self.deref(sub)
                    label = (d.get("title")
                             or (d.get("description") or "").split("—")[0].strip()[:52]
                             or f"form {i + 1}")
                    out.append((label, d))
                return out
        return [("", n)]

    def child_keys(self, node):
        props = dict(node.get("properties") or {})
        if props:
            return props, False
        #: `additionalProperties` IS the value's schema; `patternProperties` is a MAP of pattern to
        #: schema, so only the second needs unwrapping. Conflating them turned
        #: `additionalProperties: {"type": "string"}` into the string `"string"`, which is not a node
        #: — so three free-key levels could never carry a description and showed as permanent gaps.
        h = node.get("additionalProperties")
        if isinstance(h, dict) and h:
            return {ANY: h}, True
        h = node.get("patternProperties")
        if isinstance(h, dict) and h:
            return {ANY: list(h.values())[0]}, True
        return {}, False

    def type_of(self, resolved, raw):
        if isinstance(raw, dict) and raw.get("type") == "array":
            return f"list of {self.deref(raw).get('type') or 'object'}"
        return resolved.get("type") or (raw.get("type") if isinstance(raw, dict) else None) or "—"

    def walk(self, node, path: str, depth: int = 0):
        if depth > 8 or path in self.levels:
            return
        forms = []
        for label, resolved in self.shapes(node):
            props, is_map = self.child_keys(resolved)
            if props:
                forms.append((label, resolved, props, is_map))
        if not forms:
            return

        self.levels[path] = {"path": path, "forms": [], "depth": depth}
        for label, resolved, props, is_map in forms:
            required = set(resolved.get("required") or [])
            keys = []
            for key, raw in props.items():
                res = self.deref(raw)
                desc = (raw.get("description") if isinstance(raw, dict) else None) or res.get("description")
                enum = res.get("enum") or (raw.get("enum") if isinstance(raw, dict) else None)
                child = f"{path}.{key}"
                has_children = bool(self.child_keys(res)[0]) or len(self.shapes(raw)) > 1
                if not desc:
                    self.gaps.append({"level": path, "key": key})
                keys.append({
                    "key": key, "required": key in required,
                    "type": self.type_of(res, raw if isinstance(raw, dict) else {}),
                    "desc": desc,
                    "enum": [(e, self.dotted.get(e)) for e in enum] if enum else None,
                    "child": child if has_children else None,
                })
                self.walk(raw, child, depth + 1)
            self.levels[path]["forms"].append({
                "label": label, "free_key_map": is_map,
                "description": resolved.get("description"),
                "keys": sorted(keys, key=lambda k: (not k["required"], k["key"])),
            })


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# examples, cut from real concepts
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def cut_examples(bundle: pathlib.Path, limit_chars: int = 1400):
    """{level path -> {concept, yaml}} — an example a person TYPED would be another home."""
    examples: dict[str, dict] = {}
    read: list[str] = []
    concepts = bundle / "ontology" / "concepts"
    if not concepts.is_dir():
        return examples, read

    def collect(obj, path, name):
        if path not in examples and isinstance(obj, (dict, list)) and obj:
            text = yaml.safe_dump(obj, sort_keys=False, allow_unicode=True, width=86).rstrip()
            if len(text) <= limit_chars:
                examples[path] = {"concept": name, "yaml": text}
        if isinstance(obj, dict):
            for k, v in obj.items():
                collect(v, f"{path}.{k}", name)
        elif isinstance(obj, list) and obj:
            collect(obj[0], path, name)

    for f in sorted(concepts.glob("*.yaml")):
        try:
            doc = yaml.safe_load(f.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            continue
        name = (doc.get("concept") or {}).get("name") or f.stem
        read.append(name)
        for top, val in doc.items():
            collect(val, f"concept.{top}", name)
        for src in ((doc.get("grounding") or {}).get("sources") or []):
            cols = src.get("columns")
            if isinstance(cols, dict):
                for spec in cols.values():
                    collect(spec, f"concept.grounding.sources.columns.{ANY}", name)
                    break
    return examples, read


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# rendering
# ──────────────────────────────────────────────────────────────────────────────────────────────────

#: ONE DIRECTORY PER LEVEL, because a menu is built from the FILE TREE. 58 pages named
#: `concept.grounding.sources.columns.each.measure.md` in one directory give every viewer — the
#: console's own panel included — 58 flat siblings, which is the defect this reference exists to
#: end, committed in the filesystem instead of in prose. Nested directories make any file-tree menu
#: hierarchical with no code in the viewer at all. A level with children owns a directory and is
#: its `README.md`; a leaf is a file beside its siblings.

def level_page(path: str, levels) -> str:
    segs = [ANY_SLUG if s == ANY else s for s in path.split(".")]
    has_children = any(p.startswith(path + ".") for p in levels)
    return "/".join(segs) + ("/README.md" if has_children else ".md")


def notion_page(notion: str, notions) -> str:
    segs = ["vocabulary"] + notion.split(".")
    has_children = any(n.startswith(notion + ".") for n in notions)
    return "/".join(segs) + ("/README.md" if has_children else ".md")


def rel(here: str, there: str) -> str:
    """A link from one page to another, both keys-relative. Nested pages need `../`."""
    import posixpath
    return posixpath.relpath(there, posixpath.dirname(here)) or "."


def cell(text) -> str:
    """One table cell: pipes escaped and newlines folded, or a table breaks in half."""
    s = " ".join(str(text or "").split())
    return s.replace("|", "\\|")


def render_level(path, level, levels, notions, examples, gaps_by_level, bundle_name) -> str:
    here = level_page(path, levels)
    segs = path.split(".")
    crumb = []
    for i in range(len(segs)):
        p = ".".join(segs[:i + 1])
        crumb.append(segs[i] if i == len(segs) - 1
                     else (f"[{segs[i]}]({rel(here, level_page(p, levels))})"
                           if p in levels else segs[i]))

    out = [BANNER, "", f"# `{path}`", "", " · ".join(crumb), ""]

    description = next((f["description"] for f in level["forms"] if f.get("description")), None)
    if description:
        out += [description.strip(), ""]

    n_gap = len(gaps_by_level.get(path, ()))
    if n_gap:
        out += [f"> **{n_gap} key{'s' if n_gap > 1 else ''} at this level carry no description in "
                f"`mac.schema.json`.** They are marked `— gap —` below. The place to fix one is the "
                f"schema, which is its one home; this page is generated and cannot hold the answer.",
                ""]

    for i, form in enumerate(level["forms"], 1):
        if len(level["forms"]) > 1:
            out += [f"## Form {i}" + (f" — {form['label']}" if form["label"] else ""), ""]
            if form["description"]:
                out += [form["description"].strip(), ""]
        else:
            out += ["## Keys you may write here", ""]

        if form["free_key_map"]:
            out += [f"You choose the names at this level — a column name, an axis name. "
                    f"`{ANY}` below stands for any one of them.", ""]

        out += ["| key | | type | what it means | goes deeper |",
                "|---|---|---|---|---|"]
        for k in form["keys"]:
            meaning = cell(k["desc"]) if k["desc"] else "— gap —"
            if k["enum"]:
                values = []
                for value, term in k["enum"]:
                    if term and term.get("notion"):
                        target = rel(here, notion_page(term["notion"], notions))
                        values.append(f"[`{value}`]({target}#{term['term']})")
                    else:
                        values.append(f"`{value}`")
                meaning += "<br>**one of:** " + " · ".join(values)
            deeper = (f"[{k['child'].split('.')[-1]}]"
                      f"({rel(here, level_page(k['child'], levels))})") if k["child"] else ""
            out.append(f"| `{k['key']}` | {'**required**' if k['required'] else ''} | "
                       f"`{k['type']}` | {meaning} | {deeper} |")
        out.append("")

    example = examples.get(path)
    if example:
        out += ["## As it is actually written", "",
                f"Cut from **{example['concept']}** in the `{bundle_name}` bundle — not typed by hand.",
                "", "```yaml", example["yaml"], "```", ""]

    children = sorted(p for p in levels
                      if p.startswith(path + ".") and "." not in p[len(path) + 1:])
    if children:
        out += ["## Levels under this one", ""]
        out += [f"- [`{p.split('.')[-1]}:`]({rel(here, level_page(p, levels))})" for p in children]
        out.append("")

    out += ["---", "", f"[↑ the whole tree]({rel(here, 'README.md')})", ""]
    return "\n".join(out)


def render_notion(notion, body, levels, notions) -> str:
    here = notion_page(notion, notions)
    out = [BANNER, "", f"# `mac.{notion}.<term>`", "",
           ("**Closed** — these are all of them. A value outside this list is a load error, "
            "not a new term." if body["closed"] else "**Open** — terms may be added.")
           + f"  ·  {len(body['terms'])} terms", ""]
    if body["description"]:
        out += [body["description"].strip(), ""]

    out += ["## Terms", "", "| term | write it as | what it means |", "|---|---|---|"]
    for term, entry in body["terms"].items():
        extra = entry.get("extra") or {}
        meaning = cell(entry["definition"]) if entry["definition"] else "— no definition —"
        if extra:
            meaning += "<br>" + " · ".join(
                f"`{k}`: {cell(json.dumps(v) if not isinstance(v, str) else v)}"
                for k, v in extra.items())
        out.append(f"| <a id=\"{term}\"></a>`{term}` | `mac.{notion}.{term}` | {meaning} |")
    out.append("")

    takers = []
    for path, level in levels.items():
        for form in level["forms"]:
            for k in form["keys"]:
                if not k["enum"]:
                    continue
                for value, term in k["enum"]:
                    if (term or {}).get("notion") == notion:
                        takers.append((path, k["key"]))
                        break
    takers = sorted(set(takers))
    if takers:
        out += ["## Keys that take one of these values", ""]
        out += [f"- `{k}` on [`{p}`]({rel(here, level_page(p, levels))})" for p, k in takers]
        out.append("")

    out += ["---", "", f"[↑ the whole tree]({rel(here, 'README.md')})", ""]
    return "\n".join(out)


def render_index(levels, notions, gaps, examples, schema_version, bundle_name, concepts_read) -> str:
    key_total = sum(len(f["keys"]) for lv in levels.values() for f in lv["forms"])
    described = key_total - len(gaps)
    out = [BANNER, "", "# The key reference", "",
           "Every key a concept file may write, one page per level, and one DIRECTORY per level so "
           "that any file-tree menu shows the hierarchy. Start at "
           f"[`concept`]({level_page('concept', levels)}) — the file itself — and walk down: each page lists the keys "
           "legal at that level, what each means, which are required, the legal values of each, "
           "and the level beneath it.", "",
           f"Generated from `mac.schema.json` **{schema_version}** and `mac_vocabulary.yaml`. "
           f"Examples are cut from {len(concepts_read)} real concepts in the `{bundle_name}` "
           "bundle. Nothing on these pages is authored prose — see "
           "`tools/gen_key_reference.py` for why.", "",
           "| | |", "|---|---|",
           f"| levels | {len(levels)} |",
           f"| keys | {key_total} |",
           f"| described in the schema | **{described} of {key_total}** "
           f"({round(100 * described / max(key_total, 1))}%) |",
           f"| **gaps — admitted and unexplained** | **{len(gaps)}** |",
           f"| vocabularies | {len(notions)}, "
           f"{sum(len(n['terms']) for n in notions.values())} terms |",
           f"| examples | {len(examples)} |", ""]

    gaps_by_level: dict[str, int] = {}
    for g in gaps:
        gaps_by_level[g["level"]] = gaps_by_level.get(g["level"], 0) + 1

    #: THE INDEX IS THE MENU, SO IT IS NESTED. A flat list of 34 dotted paths is the defect this
    #: whole reference exists to end, one level up: a reader scanning
    #: `concept.grounding.sources.columns.<name>.rulings` beside `concept.values.aliases.map` has
    #: to parse both strings to learn they are not siblings. Indentation carries the nesting, so
    #: the LAST segment is the label and the full path is the link's own text on arrival.
    out += ["## The levels", "",
            "Indented by nesting. The label is the key; the page it opens is that key's level.", ""]

    def level_tree(parent: str, depth: int):
        kids = sorted(p for p in levels
                      if p.startswith(parent + ".") and "." not in p[len(parent) + 1:])
        for path in kids:
            n_keys = sum(len(f["keys"]) for f in levels[path]["forms"])
            n_gap = gaps_by_level.get(path, 0)
            note = f"{n_keys} key" + ("s" if n_keys != 1 else "")
            if n_gap:
                note += f", **{n_gap} unexplained**"
            # The label is the YAML key as it is actually typed, colon and all — `grounding:` —
            # because the root is the FILE and `concept:` is one block inside it, and a tree whose
            # first two rows both read "concept" makes a reader check which is which every time.
            leaf = path.rsplit(".", 1)[-1]
            label = leaf if leaf == ANY else f"{leaf}:"
            out.append(f"{'  ' * depth}- [`{label}`]({level_page(path, levels)}) — {note}")
            level_tree(path, depth + 1)

    root_keys = sum(len(f["keys"]) for f in levels["concept"]["forms"])
    root_gap = gaps_by_level.get("concept", 0)
    out.append(f"- [**a concept file**]({level_page('concept', levels)}) — its {root_keys} top-level keys"
               + (f", **{root_gap} unexplained**" if root_gap else ""))
    level_tree("concept", 1)
    out.append("")

    out += ["## The vocabularies and the predefined types", "",
            "A value like `mac.concept.column.measure_type.flow` is the notion "
            "`concept.column.measure_type` and the term `flow`. The dotted name is a hierarchy, so "
            "this is indented by it: only the leaves are pages, and a page lists every term of one "
            "notion and every key that accepts it.", "", "- `mac`"]

    #: Intermediate segments — `concept`, `concept.column` — are PATH and not notions, so they are
    #: plain text. Linking them would promise a page that does not exist.
    def notion_tree(prefix: str, depth: int):
        seen: dict[str, bool] = {}
        for notion in sorted(notions):
            if prefix and not notion.startswith(prefix + "."):
                continue
            rest = notion[len(prefix) + 1:] if prefix else notion
            head = rest.split(".", 1)[0]
            if head in seen:
                continue
            seen[head] = True
            full = f"{prefix}.{head}" if prefix else head
            pad = "  " * depth
            if full in notions:
                body = notions[full]
                out.append(f"{pad}- [`{head}`]({notion_page(full, notions)}) — {len(body['terms'])} terms"
                           + (", closed" if body["closed"] else ", open"))
            else:
                out.append(f"{pad}- `{head}`")
            notion_tree(full, depth + 1)

    notion_tree("", 1)
    out.append("")

    if gaps:
        out += ["## The gaps, by level", "",
                "Each is a key the schema admits and does not explain. The fix is a description "
                "written into `mac.schema.json`; these pages then fill themselves in.", "",
                "| level | keys with no description |", "|---|---|"]
        by: dict[str, list[str]] = {}
        for g in gaps:
            by.setdefault(g["level"], []).append(g["key"])
        # ORDERED LIKE THE TREE ABOVE, not by size. A worklist sorted biggest-first is a second
        # sequence over the same set, and a reader who has just walked the tree then has to find
        # their place again. The counts are not repeated here either — the tree carries those, this
        # carries WHICH keys, so neither is a second home for the other.
        for path in sorted(by):
            out.append(f"| [`{path}`]({level_page(path, levels)}) | "
                       f"{', '.join('`' + k + '`' for k in sorted(by[path]))} |")
        out.append("")
    return "\n".join(out)


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# the model, and the pages
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def build(root: pathlib.Path, bundle: pathlib.Path | None):
    schema, vocab = load(root)
    notions, dotted = harvest_vocabulary(vocab)
    walker = Walker(schema, dotted)
    walker.walk(walker.defs["ConceptFile"], "concept")
    examples, read = cut_examples(bundle) if bundle and bundle.is_dir() else ({}, [])
    return schema, notions, walker, examples, read


def pages_for(root: pathlib.Path, bundle: pathlib.Path | None) -> dict[str, str]:
    schema, notions, walker, examples, read = build(root, bundle)
    gaps_by_level: dict[str, list[str]] = {}
    for g in walker.gaps:
        gaps_by_level.setdefault(g["level"], []).append(g["key"])

    pages = {"README.md": render_index(walker.levels, notions, walker.gaps, examples,
                                      schema["version"], bundle.name if bundle else "none", read)}
    for path, level in walker.levels.items():
        pages[level_page(path, walker.levels)] = render_level(
            path, level, walker.levels, notions, examples, gaps_by_level,
            bundle.name if bundle else "none")
    for notion, body in notions.items():
        pages[notion_page(notion, notions)] = render_notion(notion, body, walker.levels, notions)
    return pages


def write(out_dir: pathlib.Path, pages: dict[str, str]) -> int:
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, text in pages.items():
        p = out_dir / name
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text if text.endswith("\n") else text + "\n", encoding="utf-8")
    #: PRUNE, because renaming a level leaves its old page behind and a stale page in a GENERATED
    #: tree is indistinguishable from a current one. Only `.md` under this directory is touched, and
    #: only what this run did not write.
    wanted = {out_dir / n for n in pages}
    for old in sorted(out_dir.rglob("*.md")):
        if old not in wanted:
            old.unlink()
    for d in sorted(out_dir.rglob("*"), reverse=True):
        if d.is_dir() and not any(d.iterdir()):
            d.rmdir()
    return len(pages)


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# the check — two different questions, two different rejects
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def check(root: pathlib.Path, out_dir: pathlib.Path, bundle) -> list[str]:
    schema, notions, walker, examples, read = build(root, bundle)
    pages = pages_for(root, bundle)
    rejects: list[str] = []

    on_disk = {str(p.relative_to(out_dir)) for p in out_dir.rglob("*.md")} if out_dir.is_dir() else set()

    for rel in sorted(set(pages) - on_disk):
        rejects.append(f"[missing-page] {rel} — a level the schema admits has no page; regenerate")
    for rel in sorted(on_disk - set(pages)):
        rejects.append(f"[orphan-page] {rel} — a page for a level the schema no longer admits; delete")
    for rel in sorted(set(pages) & on_disk):
        want = pages[rel]
        want = want if want.endswith("\n") else want + "\n"
        if (out_dir / rel).read_text(encoding="utf-8") != want:
            rejects.append(f"[stale-page] {rel} — the declarations moved and the page did not; regenerate")

    #: THE INDEPENDENT ASSERTION. Everything above re-renders and compares, which cannot catch the
    #: RENDERER dropping a key — `gen_schema_shapes.py` reports its page current while omitting
    #: `rulings` for exactly this reason. So: read the keys out of the schema walk and require each
    #: to appear, as a table cell, on the page for its own level. Different question, different
    #: evidence, so the two cannot agree by construction.
    for path, level in walker.levels.items():
        page = level_page(path, walker.levels)
        text = (out_dir / page).read_text(encoding="utf-8") if (out_dir / page).is_file() else ""
        for form in level["forms"]:
            for k in form["keys"]:
                if f"| `{k['key']}` |" not in text:
                    rejects.append(f"[uncovered-key] {path}.{k['key']} — the schema admits this key "
                                   f"and {page} does not list it")
    return rejects


# ──────────────────────────────────────────────────────────────────────────────────────────────────
# self-test — one mutant per reject class, plus a clean fixture that must pass
# ──────────────────────────────────────────────────────────────────────────────────────────────────

def self_test(bundle) -> int:
    checks = 0
    failures: list[str] = []

    def expect(cond, msg):
        nonlocal checks
        checks += 1
        if not cond:
            failures.append(msg)

    with tempfile.TemporaryDirectory() as tmp:
        out = pathlib.Path(tmp) / "keys"
        pages = pages_for(ROOT, bundle)
        write(out, pages)

        expect(check(ROOT, out, bundle) == [], "a freshly written tree must be clean")

        # stale-page
        target = out / "concept" / "README.md"
        keep = target.read_text(encoding="utf-8")
        target.write_text(keep.replace("# `concept`", "# `concept` EDITED"), encoding="utf-8")
        expect(any(r.startswith("[stale-page]") for r in check(ROOT, out, bundle)),
               "a hand-edited page must reject as stale-page")
        target.write_text(keep, encoding="utf-8")

        # missing-page
        target.unlink()
        expect(any(r.startswith("[missing-page]") for r in check(ROOT, out, bundle)),
               "a deleted page must reject as missing-page")
        target.write_text(keep, encoding="utf-8")

        # orphan-page
        stray = out / "concept" / "not_a_level.md"
        stray.write_text("stray\n", encoding="utf-8")
        expect(any(r.startswith("[orphan-page]") for r in check(ROOT, out, bundle)),
               "a page for no level must reject as orphan-page")
        stray.unlink()

        # uncovered-key — the renderer silently dropping a key the schema admits
        gutted = "\n".join(ln for ln in keep.splitlines() if not ln.startswith("| `grounding`"))
        target.write_text(gutted + "\n", encoding="utf-8")
        rejects = check(ROOT, out, bundle)
        expect(any(r.startswith("[uncovered-key]") for r in rejects),
               "a key the schema admits and the page omits must reject as uncovered-key")
        target.write_text(keep, encoding="utf-8")

        expect(check(ROOT, out, bundle) == [], "restoring every mutant must return to clean")

    if failures:
        for f in failures:
            print(f"  [SELF-TEST] {f}")
        print(f"FAIL: gen_key_reference self-test — {len(failures)} of {checks} check(s) failed")
        return 1
    print(f"PASS: gen_key_reference self-test — {checks}/{checks} check(s) over 4 reject class(es)")
    return 0


def resolve_bundle(explicit: str | None) -> pathlib.Path | None:
    """Explicit, then $MAC_BUNDLE, then a worked bundle beside this checkout, then nothing.

    Nothing is LEGAL: a machine with no bundle gets pages with no examples, which is a thinner
    reference and not a broken one. The sibling lookup is `_neighbours.worked_bundles()` — one
    home for that fact, and it finds a bundle by the `mac.project.yaml` it carries rather than by
    naming a repository, so no checkout name is typed into this public repo.
    """
    import os
    for candidate in (explicit, os.environ.get("MAC_BUNDLE")):
        if candidate:
            p = pathlib.Path(candidate)
            return p if p.is_dir() else None
    sys.path.insert(0, str(SELF.parent))
    try:
        import _neighbours
    except ImportError:
        return None
    for b in reversed(_neighbours.worked_bundles()):
        if (b / "ontology" / "concepts").is_dir():
            return b
    return None


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if a page is stale, missing or incomplete")
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--bundle", help="a bundle to cut examples from (else $MAC_BUNDLE, else the sibling estate)")
    a = ap.parse_args(argv)

    bundle = resolve_bundle(a.bundle)

    if a.self_test:
        return self_test(bundle)

    if a.check:
        rejects = check(ROOT, OUT_DIR, bundle)
        pages = pages_for(ROOT, bundle)
        if rejects:
            for r in rejects[:40]:
                print(f"  {r}")
            if len(rejects) > 40:
                print(f"  … and {len(rejects) - 40} more")
            print(f"FAIL: gen_key_reference — {len(rejects)} reject(s) over {len(pages)} page(s) "
                  f"examined; run `python3 tools/gen_key_reference.py` to regenerate")
            return 1
        print(f"PASS: gen_key_reference — {len(pages)} page(s) current against mac.schema.json and "
              f"mac_vocabulary.yaml, every admitted key covered")
        return 0

    pages = pages_for(ROOT, bundle)
    n = write(OUT_DIR, pages)
    _, notions, walker, examples, read = build(ROOT, bundle)
    key_total = sum(len(f["keys"]) for lv in walker.levels.values() for f in lv["forms"])
    print(f"PASS: gen_key_reference — wrote {n} page(s) to "
          f"{OUT_DIR.relative_to(ROOT)}: {len(walker.levels)} level(s), {len(notions)} vocabular(y/ies), "
          f"{key_total} key(s) of which {key_total - len(walker.gaps)} described and "
          f"{len(walker.gaps)} unexplained; {len(examples)} example(s) cut from "
          f"{len(read)} concept(s) in {bundle.name if bundle else 'no bundle'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
